<?php

use Illuminate\Database\Seeder;
use App\Estado;
use App\Departamento;
use Database/Seeders;


class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        //definir los datos precargados en la tabla estados
        Estado::truncate();
        Estado::create(
            [

            ]
            );

            //Definir los datos precargados en la tabla departamentos.

        Departamento::truncate();
        Departamento::create([
                'codigo'=>1,	'nombre'=>'MEDELLIN',	'id_departamento'=>5,
                'codigo'=>2,	'nombre'=>'ABEJORRAL',	'id_departamento'=>5,
                'codigo'=>4,	'nombre'=>'ABRIAQUI',	'id_departamento'=>5,
                'codigo'=>21,	'nombre'=>'ALEJANDRIA',	'id_departamento'=>5,
                'codigo'=>30,	'nombre'=>'AMAGA',	'id_departamento'=>5,
                'codigo'=>31,	'nombre'=>'AMALFI',	'id_departamento'=>5,
                'codigo'=>34,	'nombre'=>'ANDES',	'id_departamento'=>5,
                'codigo'=>36,	'nombre'=>'ANGELOPOLIS',	'id_departamento'=>5,
                'codigo'=>38,	'nombre'=>'ANGOSTURA',	'id_departamento'=>5,
                'codigo'=>40,	'nombre'=>'ANORI',	'id_departamento'=>5,
                'codigo'=>42,	'nombre'=>'SANTAFE DE ANTIOQUIA',	'id_departamento'=>5,
                'codigo'=>44,	'nombre'=>'ANZA',	'id_departamento'=>5,
                'codigo'=>45,	'nombre'=>'APARTADO',	'id_departamento'=>5,
                'codigo'=>51,	'nombre'=>'ARBOLETES',	'id_departamento'=>5,
                'codigo'=>55,	'nombre'=>'ARGELIA',	'id_departamento'=>5,
                'codigo'=>59,	'nombre'=>'ARMENIA',	'id_departamento'=>5,
                'codigo'=>79,	'nombre'=>'BARBOSA',	'id_departamento'=>5,
                'codigo'=>86,	'nombre'=>'BELMIRA',	'id_departamento'=>5,
                'codigo'=>88,	'nombre'=>'BELLO',	'id_departamento'=>5,
                'codigo'=>91,	'nombre'=>'BETANIA',	'id_departamento'=>5,
                'codigo'=>93,	'nombre'=>'BETULIA',	'id_departamento'=>5,
                'codigo'=>101,	'nombre'=>'CIUDAD BOLIVAR',	'id_departamento'=>5,
                'codigo'=>107,	'nombre'=>'BRICE?O',	'id_departamento'=>5,
                'codigo'=>113,	'nombre'=>'BURITICA',	'id_departamento'=>5,
                'codigo'=>120,	'nombre'=>'CACERES',	'id_departamento'=>5,
                'codigo'=>125,	'nombre'=>'CAICEDO',	'id_departamento'=>5,
                'codigo'=>129,	'nombre'=>'CALDAS',	'id_departamento'=>5,
                'codigo'=>134,	'nombre'=>'CAMPAMENTO',	'id_departamento'=>5,
                'codigo'=>138,	'nombre'=>'CA?ASGORDAS',	'id_departamento'=>5,
                'codigo'=>142,	'nombre'=>'CARACOLI',	'id_departamento'=>5,
                'codigo'=>145,	'nombre'=>'CARAMANTA',	'id_departamento'=>5,
                'codigo'=>147,	'nombre'=>'CAREPA',	'id_departamento'=>5,
                'codigo'=>148,	'nombre'=>'EL CARMEN DE VIBORAL',	'id_departamento'=>5,
                'codigo'=>150,	'nombre'=>'CAROLINA',	'id_departamento'=>5,
                'codigo'=>154,	'nombre'=>'CAUCASIA',	'id_departamento'=>5,
                'codigo'=>172,	'nombre'=>'CHIGORODO',	'id_departamento'=>5,
                'codigo'=>190,	'nombre'=>'CISNEROS',	'id_departamento'=>5,
                'codigo'=>197,	'nombre'=>'COCORNA',	'id_departamento'=>5,
                'codigo'=>206,	'nombre'=>'CONCEPCION',	'id_departamento'=>5,
                'codigo'=>209,	'nombre'=>'CONCORDIA',	'id_departamento'=>5,
                'codigo'=>212,	'nombre'=>'COPACABANA',	'id_departamento'=>5,
                'codigo'=>234,	'nombre'=>'DABEIBA',	'id_departamento'=>5,
                'codigo'=>237,	'nombre'=>'DON MATIAS',	'id_departamento'=>5,
                'codigo'=>240,	'nombre'=>'EBEJICO',	'id_departamento'=>5,
                'codigo'=>250,	'nombre'=>'EL BAGRE',	'id_departamento'=>5,
                'codigo'=>264,	'nombre'=>'ENTRERRIOS',	'id_departamento'=>5,
                'codigo'=>266,	'nombre'=>'ENVIGADO',	'id_departamento'=>5,
                'codigo'=>282,	'nombre'=>'FREDONIA',	'id_departamento'=>5,
                'codigo'=>284,	'nombre'=>'FRONTINO',	'id_departamento'=>5,
                'codigo'=>306,	'nombre'=>'GIRALDO',	'id_departamento'=>5,
                'codigo'=>308,	'nombre'=>'GIRARDOTA',	'id_departamento'=>5,
                'codigo'=>310,	'nombre'=>'GOMEZ PLATA',	'id_departamento'=>5,
                'codigo'=>313,	'nombre'=>'GRANADA',	'id_departamento'=>5,
                'codigo'=>315,	'nombre'=>'GUADALUPE',	'id_departamento'=>5,
                'codigo'=>318,	'nombre'=>'GUARNE',	'id_departamento'=>5,
                'codigo'=>321,	'nombre'=>'GUATAPE',	'id_departamento'=>5,
                'codigo'=>347,	'nombre'=>'HELICONIA',	'id_departamento'=>5,
                'codigo'=>353,	'nombre'=>'HISPANIA',	'id_departamento'=>5,
                'codigo'=>360,	'nombre'=>'ITAGUI',	'id_departamento'=>5,
                'codigo'=>361,	'nombre'=>'ITUANGO',	'id_departamento'=>5,
                'codigo'=>364,	'nombre'=>'JARDIN',	'id_departamento'=>5,
                'codigo'=>368,	'nombre'=>'JERICO',	'id_departamento'=>5,
                'codigo'=>376,	'nombre'=>'LA CEJA',	'id_departamento'=>5,
                'codigo'=>380,	'nombre'=>'LA ESTRELLA',	'id_departamento'=>5,
                'codigo'=>390,	'nombre'=>'LA PINTADA',	'id_departamento'=>5,
                'codigo'=>400,	'nombre'=>'LA UNION',	'id_departamento'=>5,
                'codigo'=>411,	'nombre'=>'LIBORINA',	'id_departamento'=>5,
                'codigo'=>425,	'nombre'=>'MACEO',	'id_departamento'=>5,
                'codigo'=>440,	'nombre'=>'MARINILLA',	'id_departamento'=>5,
                'codigo'=>467,	'nombre'=>'MONTEBELLO',	'id_departamento'=>5,
                'codigo'=>475,	'nombre'=>'MURINDO',	'id_departamento'=>5,
                'codigo'=>480,	'nombre'=>'MUTATA',	'id_departamento'=>5,
                'codigo'=>483,	'nombre'=>'NARI?O',	'id_departamento'=>5,
                'codigo'=>490,	'nombre'=>'NECOCLI',	'id_departamento'=>5,
                'codigo'=>495,	'nombre'=>'NECHI',	'id_departamento'=>5,
                'codigo'=>501,	'nombre'=>'OLAYA',	'id_departamento'=>5,
                'codigo'=>541,	'nombre'=>'PE?OL',	'id_departamento'=>5,
                'codigo'=>543,	'nombre'=>'PEQUE',	'id_departamento'=>5,
                'codigo'=>576,	'nombre'=>'PUEBLORRICO',	'id_departamento'=>5,
                'codigo'=>579,	'nombre'=>'PUERTO BERRIO',	'id_departamento'=>5,
                'codigo'=>585,	'nombre'=>'PUERTO NARE',	'id_departamento'=>5,
                'codigo'=>591,	'nombre'=>'PUERTO TRIUNFO',	'id_departamento'=>5,
                'codigo'=>604,	'nombre'=>'REMEDIOS',	'id_departamento'=>5,
                'codigo'=>607,	'nombre'=>'RETIRO',	'id_departamento'=>5,
                'codigo'=>615,	'nombre'=>'RIONEGRO',	'id_departamento'=>5,
                'codigo'=>628,	'nombre'=>'SABANALARGA',	'id_departamento'=>5,
                'codigo'=>631,	'nombre'=>'SABANETA',	'id_departamento'=>5,
                'codigo'=>642,	'nombre'=>'SALGAR',	'id_departamento'=>5,
                'codigo'=>647,	'nombre'=>'SAN ANDRES DE CUERQUIA',	'id_departamento'=>5,
                'codigo'=>649,	'nombre'=>'SAN CARLOS',	'id_departamento'=>5,
                'codigo'=>652,	'nombre'=>'SAN FRANCISCO',	'id_departamento'=>5,
                'codigo'=>656,	'nombre'=>'SAN JERONIMO',	'id_departamento'=>5,
                'codigo'=>658,	'nombre'=>'SAN JOSE DE LA MONTA?A',	'id_departamento'=>5,
                'codigo'=>659,	'nombre'=>'SAN JUAN DE URABA',	'id_departamento'=>5,
                'codigo'=>660,	'nombre'=>'SAN LUIS',	'id_departamento'=>5,
                'codigo'=>664,	'nombre'=>'SAN PEDRO',	'id_departamento'=>5,
                'codigo'=>665,	'nombre'=>'SAN PEDRO DE URABA',	'id_departamento'=>5,
                'codigo'=>667,	'nombre'=>'SAN RAFAEL',	'id_departamento'=>5,
                'codigo'=>670,	'nombre'=>'SAN ROQUE',	'id_departamento'=>5,
                'codigo'=>674,	'nombre'=>'SAN VICENTE',	'id_departamento'=>5,
                'codigo'=>679,	'nombre'=>'SANTA BARBARA',	'id_departamento'=>5,
                'codigo'=>686,	'nombre'=>'SANTA ROSA DE OSOS',	'id_departamento'=>5,
                'codigo'=>690,	'nombre'=>'SANTO DOMINGO',	'id_departamento'=>5,
                'codigo'=>697,	'nombre'=>'EL SANTUARIO',	'id_departamento'=>5,
                'codigo'=>736,	'nombre'=>'SEGOVIA',	'id_departamento'=>5,
                'codigo'=>756,	'nombre'=>'SONSON',	'id_departamento'=>5,
                'codigo'=>761,	'nombre'=>'SOPETRAN',	'id_departamento'=>5,
                'codigo'=>789,	'nombre'=>'TAMESIS',	'id_departamento'=>5,
                'codigo'=>790,	'nombre'=>'TARAZA',	'id_departamento'=>5,
                'codigo'=>792,	'nombre'=>'TARSO',	'id_departamento'=>5,
                'codigo'=>809,	'nombre'=>'TITIRIBI',	'id_departamento'=>5,
                'codigo'=>819,	'nombre'=>'TOLEDO',	'id_departamento'=>5,
                'codigo'=>837,	'nombre'=>'TURBO',	'id_departamento'=>5,
                'codigo'=>842,	'nombre'=>'URAMITA',	'id_departamento'=>5,
                'codigo'=>847,	'nombre'=>'URRAO',	'id_departamento'=>5,
                'codigo'=>854,	'nombre'=>'VALDIVIA',	'id_departamento'=>5,
                'codigo'=>856,	'nombre'=>'VALPARAISO',	'id_departamento'=>5,
                'codigo'=>858,	'nombre'=>'VEGACHI',	'id_departamento'=>5,
                'codigo'=>861,	'nombre'=>'VENECIA',	'id_departamento'=>5,
                'codigo'=>873,	'nombre'=>'VIGIA DEL FUERTE',	'id_departamento'=>5,
                'codigo'=>885,	'nombre'=>'YALI',	'id_departamento'=>5,
                'codigo'=>887,	'nombre'=>'YARUMAL',	'id_departamento'=>5,
                'codigo'=>890,	'nombre'=>'YOLOMBO',	'id_departamento'=>5,
                'codigo'=>893,	'nombre'=>'YONDO',	'id_departamento'=>5,
                'codigo'=>895,	'nombre'=>'ZARAGOZA',	'id_departamento'=>5,
                'codigo'=>1,	'nombre'=>'BARRANQUILLA',	'id_departamento'=>8,
                'codigo'=>78,	'nombre'=>'BARANOA',	'id_departamento'=>8,
                'codigo'=>137,	'nombre'=>'CAMPO DE LA CRUZ',	'id_departamento'=>8,
                'codigo'=>141,	'nombre'=>'CANDELARIA',	'id_departamento'=>8,
                'codigo'=>296,	'nombre'=>'GALAPA',	'id_departamento'=>8,
                'codigo'=>372,	'nombre'=>'JUAN DE ACOSTA',	'id_departamento'=>8,
                'codigo'=>421,	'nombre'=>'LURUACO',	'id_departamento'=>8,
                'codigo'=>433,	'nombre'=>'MALAMBO',	'id_departamento'=>8,
                'codigo'=>436,	'nombre'=>'MANATI',	'id_departamento'=>8,
                'codigo'=>520,	'nombre'=>'PALMAR DE VARELA',	'id_departamento'=>8,
                'codigo'=>549,	'nombre'=>'PIOJO',	'id_departamento'=>8,
                'codigo'=>558,	'nombre'=>'POLONUEVO',	'id_departamento'=>8,
                'codigo'=>560,	'nombre'=>'PONEDERA',	'id_departamento'=>8,
                'codigo'=>573,	'nombre'=>'PUERTO COLOMBIA',	'id_departamento'=>8,
                'codigo'=>606,	'nombre'=>'REPELON',	'id_departamento'=>8,
                'codigo'=>634,	'nombre'=>'SABANAGRANDE',	'id_departamento'=>8,
                'codigo'=>638,	'nombre'=>'SABANALARGA',	'id_departamento'=>8,
                'codigo'=>675,	'nombre'=>'SANTA LUCIA',	'id_departamento'=>8,
                'codigo'=>685,	'nombre'=>'SANTO TOMAS',	'id_departamento'=>8,
                'codigo'=>758,	'nombre'=>'SOLEDAD',	'id_departamento'=>8,
                'codigo'=>770,	'nombre'=>'SUAN',	'id_departamento'=>8,
                'codigo'=>832,	'nombre'=>'TUBARA',	'id_departamento'=>8,
                'codigo'=>849,	'nombre'=>'USIACURI',	'id_departamento'=>8,
                'codigo'=>1,	'nombre'=>'BOGOTA, D.C.',	'id_departamento'=>11,
                'codigo'=>1,	'nombre'=>'CARTAGENA',	'id_departamento'=>13,
                'codigo'=>6,	'nombre'=>'ACHI',	'id_departamento'=>13,
                'codigo'=>30,	'nombre'=>'ALTOS DEL ROSARIO',	'id_departamento'=>13,
                'codigo'=>42,	'nombre'=>'ARENAL',	'id_departamento'=>13,
                'codigo'=>52,	'nombre'=>'ARJONA',	'id_departamento'=>13,
                'codigo'=>62,	'nombre'=>'ARROYOHONDO',	'id_departamento'=>13,
                'codigo'=>74,	'nombre'=>'BARRANCO DE LOBA',	'id_departamento'=>13,
                'codigo'=>140,	'nombre'=>'CALAMAR',	'id_departamento'=>13,
                'codigo'=>160,	'nombre'=>'CANTAGALLO',	'id_departamento'=>13,
                'codigo'=>188,	'nombre'=>'CICUCO',	'id_departamento'=>13,
                'codigo'=>212,	'nombre'=>'CORDOBA',	'id_departamento'=>13,
                'codigo'=>222,	'nombre'=>'CLEMENCIA',	'id_departamento'=>13,
                'codigo'=>244,	'nombre'=>'EL CARMEN DE BOLIVAR',	'id_departamento'=>13,
                'codigo'=>248,	'nombre'=>'EL GUAMO',	'id_departamento'=>13,
                'codigo'=>268,	'nombre'=>'EL PE?ON',	'id_departamento'=>13,
                'codigo'=>300,	'nombre'=>'HATILLO DE LOBA',	'id_departamento'=>13,
                'codigo'=>430,	'nombre'=>'MAGANGUE',	'id_departamento'=>13,
                'codigo'=>433,	'nombre'=>'MAHATES',	'id_departamento'=>13,
                'codigo'=>440,	'nombre'=>'MARGARITA',	'id_departamento'=>13,
                'codigo'=>442,	'nombre'=>'MARIA LA BAJA',	'id_departamento'=>13,
                'codigo'=>458,	'nombre'=>'MONTECRISTO',	'id_departamento'=>13,
                'codigo'=>468,	'nombre'=>'MOMPOS',	'id_departamento'=>13,
                'codigo'=>490,	'nombre'=>'NOROSI',	'id_departamento'=>13,
                'codigo'=>473,	'nombre'=>'MORALES',	'id_departamento'=>13,
                'codigo'=>549,	'nombre'=>'PINILLOS',	'id_departamento'=>13,
                'codigo'=>580,	'nombre'=>'REGIDOR',	'id_departamento'=>13,
                'codigo'=>600,	'nombre'=>'RIO VIEJO',	'id_departamento'=>13,
                'codigo'=>620,	'nombre'=>'SAN CRISTOBAL',	'id_departamento'=>13,
                'codigo'=>647,	'nombre'=>'SAN ESTANISLAO',	'id_departamento'=>13,
                'codigo'=>650,	'nombre'=>'SAN FERNANDO',	'id_departamento'=>13,
                'codigo'=>654,	'nombre'=>'SAN JACINTO',	'id_departamento'=>13,
                'codigo'=>655,	'nombre'=>'SAN JACINTO DEL CAUCA',	'id_departamento'=>13,
                'codigo'=>657,	'nombre'=>'SAN JUAN NEPOMUCENO',	'id_departamento'=>13,
                'codigo'=>667,	'nombre'=>'SAN MARTIN DE LOBA',	'id_departamento'=>13,
                'codigo'=>670,	'nombre'=>'SAN PABLO',	'id_departamento'=>13,
                'codigo'=>673,	'nombre'=>'SANTA CATALINA',	'id_departamento'=>13,
                'codigo'=>683,	'nombre'=>'SANTA ROSA',	'id_departamento'=>13,
                'codigo'=>688,	'nombre'=>'SANTA ROSA DEL SUR',	'id_departamento'=>13,
                'codigo'=>744,	'nombre'=>'SIMITI',	'id_departamento'=>13,
                'codigo'=>760,	'nombre'=>'SOPLAVIENTO',	'id_departamento'=>13,
                'codigo'=>780,	'nombre'=>'TALAIGUA NUEVO',	'id_departamento'=>13,
                'codigo'=>810,	'nombre'=>'TIQUISIO',	'id_departamento'=>13,
                'codigo'=>836,	'nombre'=>'TURBACO',	'id_departamento'=>13,
                'codigo'=>838,	'nombre'=>'TURBANA',	'id_departamento'=>13,
                'codigo'=>873,	'nombre'=>'VILLANUEVA',	'id_departamento'=>13,
                'codigo'=>894,	'nombre'=>'ZAMBRANO',	'id_departamento'=>13,
                'codigo'=>1,	'nombre'=>'TUNJA',	'id_departamento'=>15,
                'codigo'=>22,	'nombre'=>'ALMEIDA',	'id_departamento'=>15,
                'codigo'=>47,	'nombre'=>'AQUITANIA',	'id_departamento'=>15,
                'codigo'=>51,	'nombre'=>'ARCABUCO',	'id_departamento'=>15,
                'codigo'=>87,	'nombre'=>'BELEN',	'id_departamento'=>15,
                'codigo'=>90,	'nombre'=>'BERBEO',	'id_departamento'=>15,
                'codigo'=>92,	'nombre'=>'BETEITIVA',	'id_departamento'=>15,
                'codigo'=>97,	'nombre'=>'BOAVITA',	'id_departamento'=>15,
                'codigo'=>104,	'nombre'=>'BOYACA',	'id_departamento'=>15,
                'codigo'=>106,	'nombre'=>'BRICE?O',	'id_departamento'=>15,
                'codigo'=>109,	'nombre'=>'BUENAVISTA',	'id_departamento'=>15,
                'codigo'=>114,	'nombre'=>'BUSBANZA',	'id_departamento'=>15,
                'codigo'=>131,	'nombre'=>'CALDAS',	'id_departamento'=>15,
                'codigo'=>135,	'nombre'=>'CAMPOHERMOSO',	'id_departamento'=>15,
                'codigo'=>162,	'nombre'=>'CERINZA',	'id_departamento'=>15,
                'codigo'=>172,	'nombre'=>'CHINAVITA',	'id_departamento'=>15,
                'codigo'=>176,	'nombre'=>'CHIQUINQUIRA',	'id_departamento'=>15,
                'codigo'=>180,	'nombre'=>'CHISCAS',	'id_departamento'=>15,
                'codigo'=>183,	'nombre'=>'CHITA',	'id_departamento'=>15,
                'codigo'=>185,	'nombre'=>'CHITARAQUE',	'id_departamento'=>15,
                'codigo'=>187,	'nombre'=>'CHIVATA',	'id_departamento'=>15,
                'codigo'=>189,	'nombre'=>'CIENEGA',	'id_departamento'=>15,
                'codigo'=>204,	'nombre'=>'COMBITA',	'id_departamento'=>15,
                'codigo'=>212,	'nombre'=>'COPER',	'id_departamento'=>15,
                'codigo'=>215,	'nombre'=>'CORRALES',	'id_departamento'=>15,
                'codigo'=>218,	'nombre'=>'COVARACHIA',	'id_departamento'=>15,
                'codigo'=>223,	'nombre'=>'CUBARA',	'id_departamento'=>15,
                'codigo'=>224,	'nombre'=>'CUCAITA',	'id_departamento'=>15,
                'codigo'=>226,	'nombre'=>'CUITIVA',	'id_departamento'=>15,
                'codigo'=>232,	'nombre'=>'CHIQUIZA',	'id_departamento'=>15,
                'codigo'=>236,	'nombre'=>'CHIVOR',	'id_departamento'=>15,
                'codigo'=>238,	'nombre'=>'DUITAMA',	'id_departamento'=>15,
                'codigo'=>244,	'nombre'=>'EL COCUY',	'id_departamento'=>15,
                'codigo'=>248,	'nombre'=>'EL ESPINO',	'id_departamento'=>15,
                'codigo'=>272,	'nombre'=>'FIRAVITOBA',	'id_departamento'=>15,
                'codigo'=>276,	'nombre'=>'FLORESTA',	'id_departamento'=>15,
                'codigo'=>293,	'nombre'=>'GACHANTIVA',	'id_departamento'=>15,
                'codigo'=>296,	'nombre'=>'GAMEZA',	'id_departamento'=>15,
                'codigo'=>299,	'nombre'=>'GARAGOA',	'id_departamento'=>15,
                'codigo'=>317,	'nombre'=>'GUACAMAYAS',	'id_departamento'=>15,
                'codigo'=>322,	'nombre'=>'GUATEQUE',	'id_departamento'=>15,
                'codigo'=>325,	'nombre'=>'GUAYATA',	'id_departamento'=>15,
                'codigo'=>332,	'nombre'=>'GsICAN',	'id_departamento'=>15,
                'codigo'=>362,	'nombre'=>'IZA',	'id_departamento'=>15,
                'codigo'=>367,	'nombre'=>'JENESANO',	'id_departamento'=>15,
                'codigo'=>368,	'nombre'=>'JERICO',	'id_departamento'=>15,
                'codigo'=>377,	'nombre'=>'LABRANZAGRANDE',	'id_departamento'=>15,
                'codigo'=>380,	'nombre'=>'LA CAPILLA',	'id_departamento'=>15,
                'codigo'=>401,	'nombre'=>'LA VICTORIA',	'id_departamento'=>15,
                'codigo'=>403,	'nombre'=>'LA UVITA',	'id_departamento'=>15,
                'codigo'=>407,	'nombre'=>'VILLA DE LEYVA',	'id_departamento'=>15,
                'codigo'=>425,	'nombre'=>'MACANAL',	'id_departamento'=>15,
                'codigo'=>442,	'nombre'=>'MARIPI',	'id_departamento'=>15,
                'codigo'=>455,	'nombre'=>'MIRAFLORES',	'id_departamento'=>15,
                'codigo'=>464,	'nombre'=>'MONGUA',	'id_departamento'=>15,
                'codigo'=>466,	'nombre'=>'MONGUI',	'id_departamento'=>15,
                'codigo'=>469,	'nombre'=>'MONIQUIRA',	'id_departamento'=>15,
                'codigo'=>476,	'nombre'=>'MOTAVITA',	'id_departamento'=>15,
                'codigo'=>480,	'nombre'=>'MUZO',	'id_departamento'=>15,
                'codigo'=>491,	'nombre'=>'NOBSA',	'id_departamento'=>15,
                'codigo'=>494,	'nombre'=>'NUEVO COLON',	'id_departamento'=>15,
                'codigo'=>500,	'nombre'=>'OICATA',	'id_departamento'=>15,
                'codigo'=>507,	'nombre'=>'OTANCHE',	'id_departamento'=>15,
                'codigo'=>511,	'nombre'=>'PACHAVITA',	'id_departamento'=>15,
                'codigo'=>514,	'nombre'=>'PAEZ',	'id_departamento'=>15,
                'codigo'=>516,	'nombre'=>'PAIPA',	'id_departamento'=>15,
                'codigo'=>518,	'nombre'=>'PAJARITO',	'id_departamento'=>15,
                'codigo'=>522,	'nombre'=>'PANQUEBA',	'id_departamento'=>15,
                'codigo'=>531,	'nombre'=>'PAUNA',	'id_departamento'=>15,
                'codigo'=>533,	'nombre'=>'PAYA',	'id_departamento'=>15,
                'codigo'=>537,	'nombre'=>'PAZ DE RIO',	'id_departamento'=>15,
                'codigo'=>542,	'nombre'=>'PESCA',	'id_departamento'=>15,
                'codigo'=>550,	'nombre'=>'PISBA',	'id_departamento'=>15,
                'codigo'=>572,	'nombre'=>'PUERTO BOYACA',	'id_departamento'=>15,
                'codigo'=>580,	'nombre'=>'QUIPAMA',	'id_departamento'=>15,
                'codigo'=>599,	'nombre'=>'RAMIRIQUI',	'id_departamento'=>15,
                'codigo'=>600,	'nombre'=>'RAQUIRA',	'id_departamento'=>15,
                'codigo'=>621,	'nombre'=>'RONDON',	'id_departamento'=>15,
                'codigo'=>632,	'nombre'=>'SABOYA',	'id_departamento'=>15,
                'codigo'=>638,	'nombre'=>'SACHICA',	'id_departamento'=>15,
                'codigo'=>646,	'nombre'=>'SAMACA',	'id_departamento'=>15,
                'codigo'=>660,	'nombre'=>'SAN EDUARDO',	'id_departamento'=>15,
                'codigo'=>664,	'nombre'=>'SAN JOSE DE PARE',	'id_departamento'=>15,
                'codigo'=>667,	'nombre'=>'SAN LUIS DE GACENO',	'id_departamento'=>15,
                'codigo'=>673,	'nombre'=>'SAN MATEO',	'id_departamento'=>15,
                'codigo'=>676,	'nombre'=>'SAN MIGUEL DE SEMA',	'id_departamento'=>15,
                'codigo'=>681,	'nombre'=>'SAN PABLO DE BORBUR',	'id_departamento'=>15,
                'codigo'=>686,	'nombre'=>'SANTANA',	'id_departamento'=>15,
                'codigo'=>690,	'nombre'=>'SANTA MARIA',	'id_departamento'=>15,
                'codigo'=>693,	'nombre'=>'SANTA ROSA DE VITERBO',	'id_departamento'=>15,
                'codigo'=>696,	'nombre'=>'SANTA SOFIA',	'id_departamento'=>15,
                'codigo'=>720,	'nombre'=>'SATIVANORTE',	'id_departamento'=>15,
                'codigo'=>723,	'nombre'=>'SATIVASUR',	'id_departamento'=>15,
                'codigo'=>740,	'nombre'=>'SIACHOQUE',	'id_departamento'=>15,
                'codigo'=>753,	'nombre'=>'SOATA',	'id_departamento'=>15,
                'codigo'=>755,	'nombre'=>'SOCOTA',	'id_departamento'=>15,
                'codigo'=>757,	'nombre'=>'SOCHA',	'id_departamento'=>15,
                'codigo'=>759,	'nombre'=>'SOGAMOSO',	'id_departamento'=>15,
                'codigo'=>761,	'nombre'=>'SOMONDOCO',	'id_departamento'=>15,
                'codigo'=>762,	'nombre'=>'SORA',	'id_departamento'=>15,
                'codigo'=>763,	'nombre'=>'SOTAQUIRA',	'id_departamento'=>15,
                'codigo'=>764,	'nombre'=>'SORACA',	'id_departamento'=>15,
                'codigo'=>774,	'nombre'=>'SUSACON',	'id_departamento'=>15,
                'codigo'=>776,	'nombre'=>'SUTAMARCHAN',	'id_departamento'=>15,
                'codigo'=>778,	'nombre'=>'SUTATENZA',	'id_departamento'=>15,
                'codigo'=>790,	'nombre'=>'TASCO',	'id_departamento'=>15,
                'codigo'=>798,	'nombre'=>'TENZA',	'id_departamento'=>15,
                'codigo'=>804,	'nombre'=>'TIBANA',	'id_departamento'=>15,
                'codigo'=>806,	'nombre'=>'TIBASOSA',	'id_departamento'=>15,
                'codigo'=>808,	'nombre'=>'TINJACA',	'id_departamento'=>15,
                'codigo'=>810,	'nombre'=>'TIPACOQUE',	'id_departamento'=>15,
                'codigo'=>814,	'nombre'=>'TOCA',	'id_departamento'=>15,
                'codigo'=>816,	'nombre'=>'TOGsI',	'id_departamento'=>15,
                'codigo'=>820,	'nombre'=>'TOPAGA',	'id_departamento'=>15,
                'codigo'=>822,	'nombre'=>'TOTA',	'id_departamento'=>15,
                'codigo'=>832,	'nombre'=>'TUNUNGUA',	'id_departamento'=>15,
                'codigo'=>835,	'nombre'=>'TURMEQUE',	'id_departamento'=>15,
                'codigo'=>837,	'nombre'=>'TUTA',	'id_departamento'=>15,
                'codigo'=>839,	'nombre'=>'TUTAZA',	'id_departamento'=>15,
                'codigo'=>842,	'nombre'=>'UMBITA',	'id_departamento'=>15,
                'codigo'=>861,	'nombre'=>'VENTAQUEMADA',	'id_departamento'=>15,
                'codigo'=>879,	'nombre'=>'VIRACACHA',	'id_departamento'=>15,
                'codigo'=>897,	'nombre'=>'ZETAQUIRA',	'id_departamento'=>15,
                'codigo'=>1,	'nombre'=>'MANIZALES',	'id_departamento'=>17,
                'codigo'=>13,	'nombre'=>'AGUADAS',	'id_departamento'=>17,
                'codigo'=>42,	'nombre'=>'ANSERMA',	'id_departamento'=>17,
                'codigo'=>50,	'nombre'=>'ARANZAZU',	'id_departamento'=>17,
                'codigo'=>88,	'nombre'=>'BELALCAZAR',	'id_departamento'=>17,
                'codigo'=>174,	'nombre'=>'CHINCHINA',	'id_departamento'=>17,
                'codigo'=>272,	'nombre'=>'FILADELFIA',	'id_departamento'=>17,
                'codigo'=>380,	'nombre'=>'LA DORADA',	'id_departamento'=>17,
                'codigo'=>388,	'nombre'=>'LA MERCED',	'id_departamento'=>17,
                'codigo'=>433,	'nombre'=>'MANZANARES',	'id_departamento'=>17,
                'codigo'=>442,	'nombre'=>'MARMATO',	'id_departamento'=>17,
                'codigo'=>444,	'nombre'=>'MARQUETALIA',	'id_departamento'=>17,
                'codigo'=>446,	'nombre'=>'MARULANDA',	'id_departamento'=>17,
                'codigo'=>486,	'nombre'=>'NEIRA',	'id_departamento'=>17,
                'codigo'=>495,	'nombre'=>'NORCASIA',	'id_departamento'=>17,
                'codigo'=>513,	'nombre'=>'PACORA',	'id_departamento'=>17,
                'codigo'=>524,	'nombre'=>'PALESTINA',	'id_departamento'=>17,
                'codigo'=>541,	'nombre'=>'PENSILVANIA',	'id_departamento'=>17,
                'codigo'=>614,	'nombre'=>'RIOSUCIO',	'id_departamento'=>17,
                'codigo'=>616,	'nombre'=>'RISARALDA',	'id_departamento'=>17,
                'codigo'=>653,	'nombre'=>'SALAMINA',	'id_departamento'=>17,
                'codigo'=>662,	'nombre'=>'SAMANA',	'id_departamento'=>17,
                'codigo'=>665,	'nombre'=>'SAN JOSE',	'id_departamento'=>17,
                'codigo'=>777,	'nombre'=>'SUPIA',	'id_departamento'=>17,
                'codigo'=>867,	'nombre'=>'VICTORIA',	'id_departamento'=>17,
                'codigo'=>873,	'nombre'=>'VILLAMARIA',	'id_departamento'=>17,
                'codigo'=>877,	'nombre'=>'VITERBO',	'id_departamento'=>17,
                'codigo'=>1,	'nombre'=>'FLORENCIA',	'id_departamento'=>18,
                'codigo'=>29,	'nombre'=>'ALBANIA',	'id_departamento'=>18,
                'codigo'=>94,	'nombre'=>'BELEN DE LOS ANDAQUIES',	'id_departamento'=>18,
                'codigo'=>150,	'nombre'=>'CARTAGENA DEL CHAIRA',	'id_departamento'=>18,
                'codigo'=>205,	'nombre'=>'CURILLO',	'id_departamento'=>18,
                'codigo'=>247,	'nombre'=>'EL DONCELLO',	'id_departamento'=>18,
                'codigo'=>256,	'nombre'=>'EL PAUJIL',	'id_departamento'=>18,
                'codigo'=>410,	'nombre'=>'LA MONTA?ITA',	'id_departamento'=>18,
                'codigo'=>460,	'nombre'=>'MILAN',	'id_departamento'=>18,
                'codigo'=>479,	'nombre'=>'MORELIA',	'id_departamento'=>18,
                'codigo'=>592,	'nombre'=>'PUERTO RICO',	'id_departamento'=>18,
                'codigo'=>610,	'nombre'=>'SAN JOSE DEL FRAGUA',	'id_departamento'=>18,
                'codigo'=>753,	'nombre'=>'SAN VICENTE DEL CAGUAN',	'id_departamento'=>18,
                'codigo'=>756,	'nombre'=>'SOLANO',	'id_departamento'=>18,
                'codigo'=>785,	'nombre'=>'SOLITA',	'id_departamento'=>18,
                'codigo'=>860,	'nombre'=>'VALPARAISO',	'id_departamento'=>18,
                'codigo'=>1,	'nombre'=>'POPAYAN',	'id_departamento'=>19,
                'codigo'=>22,	'nombre'=>'ALMAGUER',	'id_departamento'=>19,
                'codigo'=>50,	'nombre'=>'ARGELIA',	'id_departamento'=>19,
                'codigo'=>75,	'nombre'=>'BALBOA',	'id_departamento'=>19,
                'codigo'=>100,	'nombre'=>'BOLIVAR',	'id_departamento'=>19,
                'codigo'=>110,	'nombre'=>'BUENOS AIRES',	'id_departamento'=>19,
                'codigo'=>130,	'nombre'=>'CAJIBIO',	'id_departamento'=>19,
                'codigo'=>137,	'nombre'=>'CALDONO',	'id_departamento'=>19,
                'codigo'=>142,	'nombre'=>'CALOTO',	'id_departamento'=>19,
                'codigo'=>212,	'nombre'=>'CORINTO',	'id_departamento'=>19,
                'codigo'=>256,	'nombre'=>'EL TAMBO',	'id_departamento'=>19,
                'codigo'=>290,	'nombre'=>'FLORENCIA',	'id_departamento'=>19,
                'codigo'=>300,	'nombre'=>'GUACHENE',	'id_departamento'=>19,
                'codigo'=>318,	'nombre'=>'GUAPI',	'id_departamento'=>19,
                'codigo'=>355,	'nombre'=>'INZA',	'id_departamento'=>19,
                'codigo'=>364,	'nombre'=>'JAMBALO',	'id_departamento'=>19,
                'codigo'=>392,	'nombre'=>'LA SIERRA',	'id_departamento'=>19,
                'codigo'=>397,	'nombre'=>'LA VEGA',	'id_departamento'=>19,
                'codigo'=>418,	'nombre'=>'LOPEZ',	'id_departamento'=>19,
                'codigo'=>450,	'nombre'=>'MERCADERES',	'id_departamento'=>19,
                'codigo'=>455,	'nombre'=>'MIRANDA',	'id_departamento'=>19,
                'codigo'=>473,	'nombre'=>'MORALES',	'id_departamento'=>19,
                'codigo'=>513,	'nombre'=>'PADILLA',	'id_departamento'=>19,
                'codigo'=>517,	'nombre'=>'PAEZ',	'id_departamento'=>19,
                'codigo'=>532,	'nombre'=>'PATIA',	'id_departamento'=>19,
                'codigo'=>533,	'nombre'=>'PIAMONTE',	'id_departamento'=>19,
                'codigo'=>548,	'nombre'=>'PIENDAMO',	'id_departamento'=>19,
                'codigo'=>573,	'nombre'=>'PUERTO TEJADA',	'id_departamento'=>19,
                'codigo'=>585,	'nombre'=>'PURACE',	'id_departamento'=>19,
                'codigo'=>622,	'nombre'=>'ROSAS',	'id_departamento'=>19,
                'codigo'=>693,	'nombre'=>'SAN SEBASTIAN',	'id_departamento'=>19,
                'codigo'=>698,	'nombre'=>'SANTANDER DE QUILICHAO',	'id_departamento'=>19,
                'codigo'=>701,	'nombre'=>'SANTA ROSA',	'id_departamento'=>19,
                'codigo'=>743,	'nombre'=>'SILVIA',	'id_departamento'=>19,
                'codigo'=>760,	'nombre'=>'SOTARA',	'id_departamento'=>19,
                'codigo'=>780,	'nombre'=>'SUAREZ',	'id_departamento'=>19,
                'codigo'=>785,	'nombre'=>'SUCRE',	'id_departamento'=>19,
                'codigo'=>807,	'nombre'=>'TIMBIO',	'id_departamento'=>19,
                'codigo'=>809,	'nombre'=>'TIMBIQUI',	'id_departamento'=>19,
                'codigo'=>821,	'nombre'=>'TORIBIO',	'id_departamento'=>19,
                'codigo'=>824,	'nombre'=>'TOTORO',	'id_departamento'=>19,
                'codigo'=>845,	'nombre'=>'VILLA RICA',	'id_departamento'=>19,
                'codigo'=>1,	'nombre'=>'VALLEDUPAR',	'id_departamento'=>20,
                'codigo'=>11,	'nombre'=>'AGUACHICA',	'id_departamento'=>20,
                'codigo'=>13,	'nombre'=>'AGUSTIN CODAZZI',	'id_departamento'=>20,
                'codigo'=>32,	'nombre'=>'ASTREA',	'id_departamento'=>20,
                'codigo'=>45,	'nombre'=>'BECERRIL',	'id_departamento'=>20,
                'codigo'=>60,	'nombre'=>'BOSCONIA',	'id_departamento'=>20,
                'codigo'=>175,	'nombre'=>'CHIMICHAGUA',	'id_departamento'=>20,
                'codigo'=>178,	'nombre'=>'CHIRIGUANA',	'id_departamento'=>20,
                'codigo'=>228,	'nombre'=>'CURUMANI',	'id_departamento'=>20,
                'codigo'=>238,	'nombre'=>'EL COPEY',	'id_departamento'=>20,
                'codigo'=>250,	'nombre'=>'EL PASO',	'id_departamento'=>20,
                'codigo'=>295,	'nombre'=>'GAMARRA',	'id_departamento'=>20,
                'codigo'=>310,	'nombre'=>'GONZALEZ',	'id_departamento'=>20,
                'codigo'=>383,	'nombre'=>'LA GLORIA',	'id_departamento'=>20,
                'codigo'=>400,	'nombre'=>'LA JAGUA DE IBIRICO',	'id_departamento'=>20,
                'codigo'=>443,	'nombre'=>'MANAURE',	'id_departamento'=>20,
                'codigo'=>517,	'nombre'=>'PAILITAS',	'id_departamento'=>20,
                'codigo'=>550,	'nombre'=>'PELAYA',	'id_departamento'=>20,
                'codigo'=>570,	'nombre'=>'PUEBLO BELLO',	'id_departamento'=>20,
                'codigo'=>614,	'nombre'=>'RIO DE ORO',	'id_departamento'=>20,
                'codigo'=>621,	'nombre'=>'LA PAZ',	'id_departamento'=>20,
                'codigo'=>710,	'nombre'=>'SAN ALBERTO',	'id_departamento'=>20,
                'codigo'=>750,	'nombre'=>'SAN DIEGO',	'id_departamento'=>20,
                'codigo'=>770,	'nombre'=>'SAN MARTIN',	'id_departamento'=>20,
                'codigo'=>787,	'nombre'=>'TAMALAMEQUE',	'id_departamento'=>20,
                'codigo'=>1,	'nombre'=>'MONTERIA',	'id_departamento'=>23,
                'codigo'=>68,	'nombre'=>'AYAPEL',	'id_departamento'=>23,
                'codigo'=>79,	'nombre'=>'BUENAVISTA',	'id_departamento'=>23,
                'codigo'=>90,	'nombre'=>'CANALETE',	'id_departamento'=>23,
                'codigo'=>162,	'nombre'=>'CERETE',	'id_departamento'=>23,
                'codigo'=>168,	'nombre'=>'CHIMA',	'id_departamento'=>23,
                'codigo'=>182,	'nombre'=>'CHINU',	'id_departamento'=>23,
                'codigo'=>189,	'nombre'=>'CIENAGA DE ORO',	'id_departamento'=>23,
                'codigo'=>300,	'nombre'=>'COTORRA',	'id_departamento'=>23,
                'codigo'=>350,	'nombre'=>'LA APARTADA',	'id_departamento'=>23,
                'codigo'=>417,	'nombre'=>'LORICA',	'id_departamento'=>23,
                'codigo'=>419,	'nombre'=>'LOS CORDOBAS',	'id_departamento'=>23,
                'codigo'=>464,	'nombre'=>'MOMIL',	'id_departamento'=>23,
                'codigo'=>466,	'nombre'=>'MONTELIBANO',	'id_departamento'=>23,
                'codigo'=>500,	'nombre'=>'MO?ITOS',	'id_departamento'=>23,
                'codigo'=>555,	'nombre'=>'PLANETA RICA',	'id_departamento'=>23,
                'codigo'=>570,	'nombre'=>'PUEBLO NUEVO',	'id_departamento'=>23,
                'codigo'=>574,	'nombre'=>'PUERTO ESCONDIDO',	'id_departamento'=>23,
                'codigo'=>580,	'nombre'=>'PUERTO LIBERTADOR',	'id_departamento'=>23,
                'codigo'=>586,	'nombre'=>'PURISIMA',	'id_departamento'=>23,
                'codigo'=>660,	'nombre'=>'SAHAGUN',	'id_departamento'=>23,
                'codigo'=>670,	'nombre'=>'SAN ANDRES SOTAVENTO',	'id_departamento'=>23,
                'codigo'=>672,	'nombre'=>'SAN ANTERO',	'id_departamento'=>23,
                'codigo'=>675,	'nombre'=>'SAN BERNARDO DEL VIENTO',	'id_departamento'=>23,
                'codigo'=>678,	'nombre'=>'SAN CARLOS',	'id_departamento'=>23,
                'codigo'=>686,	'nombre'=>'SAN PELAYO',	'id_departamento'=>23,
                'codigo'=>807,	'nombre'=>'TIERRALTA',	'id_departamento'=>23,
                'codigo'=>855,	'nombre'=>'VALENCIA',	'id_departamento'=>23,
                'codigo'=>1,	'nombre'=>'AGUA DE DIOS',	'id_departamento'=>25,
                'codigo'=>19,	'nombre'=>'ALBAN',	'id_departamento'=>25,
                'codigo'=>35,	'nombre'=>'ANAPOIMA',	'id_departamento'=>25,
                'codigo'=>40,	'nombre'=>'ANOLAIMA',	'id_departamento'=>25,
                'codigo'=>53,	'nombre'=>'ARBELAEZ',	'id_departamento'=>25,
                'codigo'=>86,	'nombre'=>'BELTRAN',	'id_departamento'=>25,
                'codigo'=>95,	'nombre'=>'BITUIMA',	'id_departamento'=>25,
                'codigo'=>99,	'nombre'=>'BOJACA',	'id_departamento'=>25,
                'codigo'=>120,	'nombre'=>'CABRERA',	'id_departamento'=>25,
                'codigo'=>123,	'nombre'=>'CACHIPAY',	'id_departamento'=>25,
                'codigo'=>126,	'nombre'=>'CAJICA',	'id_departamento'=>25,
                'codigo'=>148,	'nombre'=>'CAPARRAPI',	'id_departamento'=>25,
                'codigo'=>151,	'nombre'=>'CAQUEZA',	'id_departamento'=>25,
                'codigo'=>154,	'nombre'=>'CARMEN DE CARUPA',	'id_departamento'=>25,
                'codigo'=>168,	'nombre'=>'CHAGUANI',	'id_departamento'=>25,
                'codigo'=>175,	'nombre'=>'CHIA',	'id_departamento'=>25,
                'codigo'=>178,	'nombre'=>'CHIPAQUE',	'id_departamento'=>25,
                'codigo'=>181,	'nombre'=>'CHOACHI',	'id_departamento'=>25,
                'codigo'=>183,	'nombre'=>'CHOCONTA',	'id_departamento'=>25,
                'codigo'=>200,	'nombre'=>'COGUA',	'id_departamento'=>25,
                'codigo'=>214,	'nombre'=>'COTA',	'id_departamento'=>25,
                'codigo'=>224,	'nombre'=>'CUCUNUBA',	'id_departamento'=>25,
                'codigo'=>245,	'nombre'=>'EL COLEGIO',	'id_departamento'=>25,
                'codigo'=>258,	'nombre'=>'EL PE?ON',	'id_departamento'=>25,
                'codigo'=>260,	'nombre'=>'EL ROSAL',	'id_departamento'=>25,
                'codigo'=>269,	'nombre'=>'FACATATIVA',	'id_departamento'=>25,
                'codigo'=>279,	'nombre'=>'FOMEQUE',	'id_departamento'=>25,
                'codigo'=>281,	'nombre'=>'FOSCA',	'id_departamento'=>25,
                'codigo'=>286,	'nombre'=>'FUNZA',	'id_departamento'=>25,
                'codigo'=>288,	'nombre'=>'FUQUENE',	'id_departamento'=>25,
                'codigo'=>290,	'nombre'=>'FUSAGASUGA',	'id_departamento'=>25,
                'codigo'=>293,	'nombre'=>'GACHALA',	'id_departamento'=>25,
                'codigo'=>295,	'nombre'=>'GACHANCIPA',	'id_departamento'=>25,
                'codigo'=>297,	'nombre'=>'GACHETA',	'id_departamento'=>25,
                'codigo'=>299,	'nombre'=>'GAMA',	'id_departamento'=>25,
                'codigo'=>307,	'nombre'=>'GIRARDOT',	'id_departamento'=>25,
                'codigo'=>312,	'nombre'=>'GRANADA',	'id_departamento'=>25,
                'codigo'=>317,	'nombre'=>'GUACHETA',	'id_departamento'=>25,
                'codigo'=>320,	'nombre'=>'GUADUAS',	'id_departamento'=>25,
                'codigo'=>322,	'nombre'=>'GUASCA',	'id_departamento'=>25,
                'codigo'=>324,	'nombre'=>'GUATAQUI',	'id_departamento'=>25,
                'codigo'=>326,	'nombre'=>'GUATAVITA',	'id_departamento'=>25,
                'codigo'=>328,	'nombre'=>'GUAYABAL DE SIQUIMA',	'id_departamento'=>25,
                'codigo'=>335,	'nombre'=>'GUAYABETAL',	'id_departamento'=>25,
                'codigo'=>339,	'nombre'=>'GUTIERREZ',	'id_departamento'=>25,
                'codigo'=>368,	'nombre'=>'JERUSALEN',	'id_departamento'=>25,
                'codigo'=>372,	'nombre'=>'JUNIN',	'id_departamento'=>25,
                'codigo'=>377,	'nombre'=>'LA CALERA',	'id_departamento'=>25,
                'codigo'=>386,	'nombre'=>'LA MESA',	'id_departamento'=>25,
                'codigo'=>394,	'nombre'=>'LA PALMA',	'id_departamento'=>25,
                'codigo'=>398,	'nombre'=>'LA PE?A',	'id_departamento'=>25,
                'codigo'=>402,	'nombre'=>'LA VEGA',	'id_departamento'=>25,
                'codigo'=>407,	'nombre'=>'LENGUAZAQUE',	'id_departamento'=>25,
                'codigo'=>426,	'nombre'=>'MACHETA',	'id_departamento'=>25,
                'codigo'=>430,	'nombre'=>'MADRID',	'id_departamento'=>25,
                'codigo'=>436,	'nombre'=>'MANTA',	'id_departamento'=>25,
                'codigo'=>438,	'nombre'=>'MEDINA',	'id_departamento'=>25,
                'codigo'=>473,	'nombre'=>'MOSQUERA',	'id_departamento'=>25,
                'codigo'=>483,	'nombre'=>'NARI?O',	'id_departamento'=>25,
                'codigo'=>486,	'nombre'=>'NEMOCON',	'id_departamento'=>25,
                'codigo'=>488,	'nombre'=>'NILO',	'id_departamento'=>25,
                'codigo'=>489,	'nombre'=>'NIMAIMA',	'id_departamento'=>25,
                'codigo'=>491,	'nombre'=>'NOCAIMA',	'id_departamento'=>25,
                'codigo'=>506,	'nombre'=>'VENECIA',	'id_departamento'=>25,
                'codigo'=>513,	'nombre'=>'PACHO',	'id_departamento'=>25,
                'codigo'=>518,	'nombre'=>'PAIME',	'id_departamento'=>25,
                'codigo'=>524,	'nombre'=>'PANDI',	'id_departamento'=>25,
                'codigo'=>530,	'nombre'=>'PARATEBUENO',	'id_departamento'=>25,
                'codigo'=>535,	'nombre'=>'PASCA',	'id_departamento'=>25,
                'codigo'=>572,	'nombre'=>'PUERTO SALGAR',	'id_departamento'=>25,
                'codigo'=>580,	'nombre'=>'PULI',	'id_departamento'=>25,
                'codigo'=>592,	'nombre'=>'QUEBRADANEGRA',	'id_departamento'=>25,
                'codigo'=>594,	'nombre'=>'QUETAME',	'id_departamento'=>25,
                'codigo'=>596,	'nombre'=>'QUIPILE',	'id_departamento'=>25,
                'codigo'=>599,	'nombre'=>'APULO',	'id_departamento'=>25,
                'codigo'=>612,	'nombre'=>'RICAURTE',	'id_departamento'=>25,
                'codigo'=>645,	'nombre'=>'SAN ANTONIO DEL TEQUENDAMA',	'id_departamento'=>25,
                'codigo'=>649,	'nombre'=>'SAN BERNARDO',	'id_departamento'=>25,
                'codigo'=>653,	'nombre'=>'SAN CAYETANO',	'id_departamento'=>25,
                'codigo'=>658,	'nombre'=>'SAN FRANCISCO',	'id_departamento'=>25,
                'codigo'=>662,	'nombre'=>'SAN JUAN DE RIO SECO',	'id_departamento'=>25,
                'codigo'=>718,	'nombre'=>'SASAIMA',	'id_departamento'=>25,
                'codigo'=>736,	'nombre'=>'SESQUILE',	'id_departamento'=>25,
                'codigo'=>740,	'nombre'=>'SIBATE',	'id_departamento'=>25,
                'codigo'=>743,	'nombre'=>'SILVANIA',	'id_departamento'=>25,
                'codigo'=>745,	'nombre'=>'SIMIJACA',	'id_departamento'=>25,
                'codigo'=>754,	'nombre'=>'SOACHA',	'id_departamento'=>25,
                'codigo'=>758,	'nombre'=>'SOPO',	'id_departamento'=>25,
                'codigo'=>769,	'nombre'=>'SUBACHOQUE',	'id_departamento'=>25,
                'codigo'=>772,	'nombre'=>'SUESCA',	'id_departamento'=>25,
                'codigo'=>777,	'nombre'=>'SUPATA',	'id_departamento'=>25,
                'codigo'=>779,	'nombre'=>'SUSA',	'id_departamento'=>25,
                'codigo'=>781,	'nombre'=>'SUTATAUSA',	'id_departamento'=>25,
                'codigo'=>785,	'nombre'=>'TABIO',	'id_departamento'=>25,
                'codigo'=>793,	'nombre'=>'TAUSA',	'id_departamento'=>25,
                'codigo'=>797,	'nombre'=>'TENA',	'id_departamento'=>25,
                'codigo'=>799,	'nombre'=>'TENJO',	'id_departamento'=>25,
                'codigo'=>805,	'nombre'=>'TIBACUY',	'id_departamento'=>25,
                'codigo'=>807,	'nombre'=>'TIBIRITA',	'id_departamento'=>25,
                'codigo'=>815,	'nombre'=>'TOCAIMA',	'id_departamento'=>25,
                'codigo'=>817,	'nombre'=>'TOCANCIPA',	'id_departamento'=>25,
                'codigo'=>823,	'nombre'=>'TOPAIPI',	'id_departamento'=>25,
                'codigo'=>839,	'nombre'=>'UBALA',	'id_departamento'=>25,
                'codigo'=>841,	'nombre'=>'UBAQUE',	'id_departamento'=>25,
                'codigo'=>843,	'nombre'=>'VILLA DE SAN DIEGO DE UBATE',	'id_departamento'=>25,
                'codigo'=>845,	'nombre'=>'UNE',	'id_departamento'=>25,
                'codigo'=>851,	'nombre'=>'UTICA',	'id_departamento'=>25,
                'codigo'=>862,	'nombre'=>'VERGARA',	'id_departamento'=>25,
                'codigo'=>867,	'nombre'=>'VIANI',	'id_departamento'=>25,
                'codigo'=>871,	'nombre'=>'VILLAGOMEZ',	'id_departamento'=>25,
                'codigo'=>873,	'nombre'=>'VILLAPINZON',	'id_departamento'=>25,
                'codigo'=>875,	'nombre'=>'VILLETA',	'id_departamento'=>25,
                'codigo'=>878,	'nombre'=>'VIOTA',	'id_departamento'=>25,
                'codigo'=>885,	'nombre'=>'YACOPI',	'id_departamento'=>25,
                'codigo'=>898,	'nombre'=>'ZIPACON',	'id_departamento'=>25,
                'codigo'=>899,	'nombre'=>'ZIPAQUIRA',	'id_departamento'=>25,
                'codigo'=>1,	'nombre'=>'QUIBDO',	'id_departamento'=>27,
                'codigo'=>6,	'nombre'=>'ACANDI',	'id_departamento'=>27,
                'codigo'=>25,	'nombre'=>'ALTO BAUDO',	'id_departamento'=>27,
                'codigo'=>50,	'nombre'=>'ATRATO',	'id_departamento'=>27,
                'codigo'=>73,	'nombre'=>'BAGADO',	'id_departamento'=>27,
                'codigo'=>75,	'nombre'=>'BAHIA SOLANO',	'id_departamento'=>27,
                'codigo'=>77,	'nombre'=>'BAJO BAUDO',	'id_departamento'=>27,
                'codigo'=>99,	'nombre'=>'BOJAYA',	'id_departamento'=>27,
                'codigo'=>135,	'nombre'=>'EL CANTON DEL SAN PABLO',	'id_departamento'=>27,
                'codigo'=>150,	'nombre'=>'CARMEN DEL DARIEN',	'id_departamento'=>27,
                'codigo'=>160,	'nombre'=>'CERTEGUI',	'id_departamento'=>27,
                'codigo'=>205,	'nombre'=>'CONDOTO',	'id_departamento'=>27,
                'codigo'=>245,	'nombre'=>'EL CARMEN DE ATRATO',	'id_departamento'=>27,
                'codigo'=>250,	'nombre'=>'EL LITORAL DEL SAN JUAN',	'id_departamento'=>27,
                'codigo'=>361,	'nombre'=>'ISTMINA',	'id_departamento'=>27,
                'codigo'=>372,	'nombre'=>'JURADO',	'id_departamento'=>27,
                'codigo'=>413,	'nombre'=>'LLORO',	'id_departamento'=>27,
                'codigo'=>425,	'nombre'=>'MEDIO ATRATO',	'id_departamento'=>27,
                'codigo'=>430,	'nombre'=>'MEDIO BAUDO',	'id_departamento'=>27,
                'codigo'=>450,	'nombre'=>'MEDIO SAN JUAN',	'id_departamento'=>27,
                'codigo'=>491,	'nombre'=>'NOVITA',	'id_departamento'=>27,
                'codigo'=>495,	'nombre'=>'NUQUI',	'id_departamento'=>27,
                'codigo'=>580,	'nombre'=>'RIO IRO',	'id_departamento'=>27,
                'codigo'=>600,	'nombre'=>'RIO QUITO',	'id_departamento'=>27,
                'codigo'=>615,	'nombre'=>'RIOSUCIO',	'id_departamento'=>27,
                'codigo'=>660,	'nombre'=>'SAN JOSE DEL PALMAR',	'id_departamento'=>27,
                'codigo'=>745,	'nombre'=>'SIPI',	'id_departamento'=>27,
                'codigo'=>787,	'nombre'=>'TADO',	'id_departamento'=>27,
                'codigo'=>800,	'nombre'=>'UNGUIA',	'id_departamento'=>27,
                'codigo'=>810,	'nombre'=>'UNION PANAMERICANA',	'id_departamento'=>27,
                'codigo'=>1,	'nombre'=>'NEIVA',	'id_departamento'=>41,
                'codigo'=>6,	'nombre'=>'ACEVEDO',	'id_departamento'=>41,
                'codigo'=>13,	'nombre'=>'AGRADO',	'id_departamento'=>41,
                'codigo'=>16,	'nombre'=>'AIPE',	'id_departamento'=>41,
                'codigo'=>20,	'nombre'=>'ALGECIRAS',	'id_departamento'=>41,
                'codigo'=>26,	'nombre'=>'ALTAMIRA',	'id_departamento'=>41,
                'codigo'=>78,	'nombre'=>'BARAYA',	'id_departamento'=>41,
                'codigo'=>132,	'nombre'=>'CAMPOALEGRE',	'id_departamento'=>41,
                'codigo'=>206,	'nombre'=>'COLOMBIA',	'id_departamento'=>41,
                'codigo'=>244,	'nombre'=>'ELIAS',	'id_departamento'=>41,
                'codigo'=>298,	'nombre'=>'GARZON',	'id_departamento'=>41,
                'codigo'=>306,	'nombre'=>'GIGANTE',	'id_departamento'=>41,
                'codigo'=>319,	'nombre'=>'GUADALUPE',	'id_departamento'=>41,
                'codigo'=>349,	'nombre'=>'HOBO',	'id_departamento'=>41,
                'codigo'=>357,	'nombre'=>'IQUIRA',	'id_departamento'=>41,
                'codigo'=>359,	'nombre'=>'ISNOS',	'id_departamento'=>41,
                'codigo'=>378,	'nombre'=>'LA ARGENTINA',	'id_departamento'=>41,
                'codigo'=>396,	'nombre'=>'LA PLATA',	'id_departamento'=>41,
                'codigo'=>483,	'nombre'=>'NATAGA',	'id_departamento'=>41,
                'codigo'=>503,	'nombre'=>'OPORAPA',	'id_departamento'=>41,
                'codigo'=>518,	'nombre'=>'PAICOL',	'id_departamento'=>41,
                'codigo'=>524,	'nombre'=>'PALERMO',	'id_departamento'=>41,
                'codigo'=>530,	'nombre'=>'PALESTINA',	'id_departamento'=>41,
                'codigo'=>548,	'nombre'=>'PITAL',	'id_departamento'=>41,
                'codigo'=>551,	'nombre'=>'PITALITO',	'id_departamento'=>41,
                'codigo'=>615,	'nombre'=>'RIVERA',	'id_departamento'=>41,
                'codigo'=>660,	'nombre'=>'SALADOBLANCO',	'id_departamento'=>41,
                'codigo'=>668,	'nombre'=>'SAN AGUSTIN',	'id_departamento'=>41,
                'codigo'=>676,	'nombre'=>'SANTA MARIA',	'id_departamento'=>41,
                'codigo'=>770,	'nombre'=>'SUAZA',	'id_departamento'=>41,
                'codigo'=>791,	'nombre'=>'TARQUI',	'id_departamento'=>41,
                'codigo'=>797,	'nombre'=>'TESALIA',	'id_departamento'=>41,
                'codigo'=>799,	'nombre'=>'TELLO',	'id_departamento'=>41,
                'codigo'=>801,	'nombre'=>'TERUEL',	'id_departamento'=>41,
                'codigo'=>807,	'nombre'=>'TIMANA',	'id_departamento'=>41,
                'codigo'=>872,	'nombre'=>'VILLAVIEJA',	'id_departamento'=>41,
                'codigo'=>885,	'nombre'=>'YAGUARA',	'id_departamento'=>41,
                'codigo'=>1,	'nombre'=>'RIOHACHA',	'id_departamento'=>44,
                'codigo'=>35,	'nombre'=>'ALBANIA',	'id_departamento'=>44,
                'codigo'=>78,	'nombre'=>'BARRANCAS',	'id_departamento'=>44,
                'codigo'=>90,	'nombre'=>'DIBULLA',	'id_departamento'=>44,
                'codigo'=>98,	'nombre'=>'DISTRACCION',	'id_departamento'=>44,
                'codigo'=>110,	'nombre'=>'EL MOLINO',	'id_departamento'=>44,
                'codigo'=>279,	'nombre'=>'FONSECA',	'id_departamento'=>44,
                'codigo'=>378,	'nombre'=>'HATONUEVO',	'id_departamento'=>44,
                'codigo'=>420,	'nombre'=>'LA JAGUA DEL PILAR',	'id_departamento'=>44,
                'codigo'=>430,	'nombre'=>'MAICAO',	'id_departamento'=>44,
                'codigo'=>560,	'nombre'=>'MANAURE',	'id_departamento'=>44,
                'codigo'=>650,	'nombre'=>'SAN JUAN DEL CESAR',	'id_departamento'=>44,
                'codigo'=>847,	'nombre'=>'URIBIA',	'id_departamento'=>44,
                'codigo'=>855,	'nombre'=>'URUMITA',	'id_departamento'=>44,
                'codigo'=>874,	'nombre'=>'VILLANUEVA',	'id_departamento'=>44,
                'codigo'=>1,	'nombre'=>'SANTA MARTA',	'id_departamento'=>47,
                'codigo'=>30,	'nombre'=>'ALGARROBO',	'id_departamento'=>47,
                'codigo'=>53,	'nombre'=>'ARACATACA',	'id_departamento'=>47,
                'codigo'=>58,	'nombre'=>'ARIGUANI',	'id_departamento'=>47,
                'codigo'=>161,	'nombre'=>'CERRO SAN ANTONIO',	'id_departamento'=>47,
                'codigo'=>170,	'nombre'=>'CHIBOLO',	'id_departamento'=>47,
                'codigo'=>189,	'nombre'=>'CIENAGA',	'id_departamento'=>47,
                'codigo'=>205,	'nombre'=>'CONCORDIA',	'id_departamento'=>47,
                'codigo'=>245,	'nombre'=>'EL BANCO',	'id_departamento'=>47,
                'codigo'=>258,	'nombre'=>'EL PI?ON',	'id_departamento'=>47,
                'codigo'=>268,	'nombre'=>'EL RETEN',	'id_departamento'=>47,
                'codigo'=>288,	'nombre'=>'FUNDACION',	'id_departamento'=>47,
                'codigo'=>318,	'nombre'=>'GUAMAL',	'id_departamento'=>47,
                'codigo'=>460,	'nombre'=>'NUEVA GRANADA',	'id_departamento'=>47,
                'codigo'=>541,	'nombre'=>'PEDRAZA',	'id_departamento'=>47,
                'codigo'=>545,	'nombre'=>'PIJI?O DEL CARMEN',	'id_departamento'=>47,
                'codigo'=>551,	'nombre'=>'PIVIJAY',	'id_departamento'=>47,
                'codigo'=>555,	'nombre'=>'PLATO',	'id_departamento'=>47,
                'codigo'=>570,	'nombre'=>'PUEBLOVIEJO',	'id_departamento'=>47,
                'codigo'=>605,	'nombre'=>'REMOLINO',	'id_departamento'=>47,
                'codigo'=>660,	'nombre'=>'SABANAS DE SAN ANGEL',	'id_departamento'=>47,
                'codigo'=>675,	'nombre'=>'SALAMINA',	'id_departamento'=>47,
                'codigo'=>692,	'nombre'=>'SAN SEBASTIAN DE BUENAVISTA',	'id_departamento'=>47,
                'codigo'=>703,	'nombre'=>'SAN ZENON',	'id_departamento'=>47,
                'codigo'=>707,	'nombre'=>'SANTA ANA',	'id_departamento'=>47,
                'codigo'=>720,	'nombre'=>'SANTA BARBARA DE PINTO',	'id_departamento'=>47,
                'codigo'=>745,	'nombre'=>'SITIONUEVO',	'id_departamento'=>47,
                'codigo'=>798,	'nombre'=>'TENERIFE',	'id_departamento'=>47,
                'codigo'=>960,	'nombre'=>'ZAPAYAN',	'id_departamento'=>47,
                'codigo'=>980,	'nombre'=>'ZONA BANANERA',	'id_departamento'=>47,
                'codigo'=>1,	'nombre'=>'VILLAVICENCIO',	'id_departamento'=>50,
                'codigo'=>6,	'nombre'=>'ACACIAS',	'id_departamento'=>50,
                'codigo'=>110,	'nombre'=>'BARRANCA DE UPIA',	'id_departamento'=>50,
                'codigo'=>124,	'nombre'=>'CABUYARO',	'id_departamento'=>50,
                'codigo'=>150,	'nombre'=>'CASTILLA LA NUEVA',	'id_departamento'=>50,
                'codigo'=>223,	'nombre'=>'CUBARRAL',	'id_departamento'=>50,
                'codigo'=>226,	'nombre'=>'CUMARAL',	'id_departamento'=>50,
                'codigo'=>245,	'nombre'=>'EL CALVARIO',	'id_departamento'=>50,
                'codigo'=>251,	'nombre'=>'EL CASTILLO',	'id_departamento'=>50,
                'codigo'=>270,	'nombre'=>'EL DORADO',	'id_departamento'=>50,
                'codigo'=>287,	'nombre'=>'FUENTE DE ORO',	'id_departamento'=>50,
                'codigo'=>313,	'nombre'=>'GRANADA',	'id_departamento'=>50,
                'codigo'=>318,	'nombre'=>'GUAMAL',	'id_departamento'=>50,
                'codigo'=>325,	'nombre'=>'MAPIRIPAN',	'id_departamento'=>50,
                'codigo'=>330,	'nombre'=>'MESETAS',	'id_departamento'=>50,
                'codigo'=>350,	'nombre'=>'LA MACARENA',	'id_departamento'=>50,
                'codigo'=>370,	'nombre'=>'URIBE',	'id_departamento'=>50,
                'codigo'=>400,	'nombre'=>'LEJANIAS',	'id_departamento'=>50,
                'codigo'=>450,	'nombre'=>'PUERTO CONCORDIA',	'id_departamento'=>50,
                'codigo'=>568,	'nombre'=>'PUERTO GAITAN',	'id_departamento'=>50,
                'codigo'=>573,	'nombre'=>'PUERTO LOPEZ',	'id_departamento'=>50,
                'codigo'=>577,	'nombre'=>'PUERTO LLERAS',	'id_departamento'=>50,
                'codigo'=>590,	'nombre'=>'PUERTO RICO',	'id_departamento'=>50,
                'codigo'=>606,	'nombre'=>'RESTREPO',	'id_departamento'=>50,
                'codigo'=>680,	'nombre'=>'SAN CARLOS DE GUAROA',	'id_departamento'=>50,
                'codigo'=>683,	'nombre'=>'SAN JUAN DE ARAMA',	'id_departamento'=>50,
                'codigo'=>686,	'nombre'=>'SAN JUANITO',	'id_departamento'=>50,
                'codigo'=>689,	'nombre'=>'SAN MARTIN',	'id_departamento'=>50,
                'codigo'=>711,	'nombre'=>'VISTAHERMOSA',	'id_departamento'=>50,
                'codigo'=>1,	'nombre'=>'PASTO',	'id_departamento'=>52,
                'codigo'=>19,	'nombre'=>'ALBAN',	'id_departamento'=>52,
                'codigo'=>22,	'nombre'=>'ALDANA',	'id_departamento'=>52,
                'codigo'=>36,	'nombre'=>'ANCUYA',	'id_departamento'=>52,
                'codigo'=>51,	'nombre'=>'ARBOLEDA',	'id_departamento'=>52,
                'codigo'=>79,	'nombre'=>'BARBACOAS',	'id_departamento'=>52,
                'codigo'=>83,	'nombre'=>'BELEN',	'id_departamento'=>52,
                'codigo'=>110,	'nombre'=>'BUESACO',	'id_departamento'=>52,
                'codigo'=>203,	'nombre'=>'COLON',	'id_departamento'=>52,
                'codigo'=>207,	'nombre'=>'CONSACA',	'id_departamento'=>52,
                'codigo'=>210,	'nombre'=>'CONTADERO',	'id_departamento'=>52,
                'codigo'=>215,	'nombre'=>'CORDOBA',	'id_departamento'=>52,
                'codigo'=>224,	'nombre'=>'CUASPUD',	'id_departamento'=>52,
                'codigo'=>227,	'nombre'=>'CUMBAL',	'id_departamento'=>52,
                'codigo'=>233,	'nombre'=>'CUMBITARA',	'id_departamento'=>52,
                'codigo'=>240,	'nombre'=>'CHACHAGsI',	'id_departamento'=>52,
                'codigo'=>250,	'nombre'=>'EL CHARCO',	'id_departamento'=>52,
                'codigo'=>254,	'nombre'=>'EL PE?OL',	'id_departamento'=>52,
                'codigo'=>256,	'nombre'=>'EL ROSARIO',	'id_departamento'=>52,
                'codigo'=>258,	'nombre'=>'EL TABLON DE GOMEZ',	'id_departamento'=>52,
                'codigo'=>260,	'nombre'=>'EL TAMBO',	'id_departamento'=>52,
                'codigo'=>287,	'nombre'=>'FUNES',	'id_departamento'=>52,
                'codigo'=>317,	'nombre'=>'GUACHUCAL',	'id_departamento'=>52,
                'codigo'=>320,	'nombre'=>'GUAITARILLA',	'id_departamento'=>52,
                'codigo'=>323,	'nombre'=>'GUALMATAN',	'id_departamento'=>52,
                'codigo'=>352,	'nombre'=>'ILES',	'id_departamento'=>52,
                'codigo'=>354,	'nombre'=>'IMUES',	'id_departamento'=>52,
                'codigo'=>356,	'nombre'=>'IPIALES',	'id_departamento'=>52,
                'codigo'=>378,	'nombre'=>'LA CRUZ',	'id_departamento'=>52,
                'codigo'=>381,	'nombre'=>'LA FLORIDA',	'id_departamento'=>52,
                'codigo'=>385,	'nombre'=>'LA LLANADA',	'id_departamento'=>52,
                'codigo'=>390,	'nombre'=>'LA TOLA',	'id_departamento'=>52,
                'codigo'=>399,	'nombre'=>'LA UNION',	'id_departamento'=>52,
                'codigo'=>405,	'nombre'=>'LEIVA',	'id_departamento'=>52,
                'codigo'=>411,	'nombre'=>'LINARES',	'id_departamento'=>52,
                'codigo'=>418,	'nombre'=>'LOS ANDES',	'id_departamento'=>52,
                'codigo'=>427,	'nombre'=>'MAGsI',	'id_departamento'=>52,
                'codigo'=>435,	'nombre'=>'MALLAMA',	'id_departamento'=>52,
                'codigo'=>473,	'nombre'=>'MOSQUERA',	'id_departamento'=>52,
                'codigo'=>480,	'nombre'=>'NARI?O',	'id_departamento'=>52,
                'codigo'=>490,	'nombre'=>'OLAYA HERRERA',	'id_departamento'=>52,
                'codigo'=>506,	'nombre'=>'OSPINA',	'id_departamento'=>52,
                'codigo'=>520,	'nombre'=>'FRANCISCO PIZARRO',	'id_departamento'=>52,
                'codigo'=>540,	'nombre'=>'POLICARPA',	'id_departamento'=>52,
                'codigo'=>560,	'nombre'=>'POTOSI',	'id_departamento'=>52,
                'codigo'=>565,	'nombre'=>'PROVIDENCIA',	'id_departamento'=>52,
                'codigo'=>573,	'nombre'=>'PUERRES',	'id_departamento'=>52,
                'codigo'=>585,	'nombre'=>'PUPIALES',	'id_departamento'=>52,
                'codigo'=>612,	'nombre'=>'RICAURTE',	'id_departamento'=>52,
                'codigo'=>621,	'nombre'=>'ROBERTO PAYAN',	'id_departamento'=>52,
                'codigo'=>678,	'nombre'=>'SAMANIEGO',	'id_departamento'=>52,
                'codigo'=>683,	'nombre'=>'SANDONA',	'id_departamento'=>52,
                'codigo'=>685,	'nombre'=>'SAN BERNARDO',	'id_departamento'=>52,
                'codigo'=>687,	'nombre'=>'SAN LORENZO',	'id_departamento'=>52,
                'codigo'=>693,	'nombre'=>'SAN PABLO',	'id_departamento'=>52,
                'codigo'=>694,	'nombre'=>'SAN PEDRO DE CARTAGO',	'id_departamento'=>52,
                'codigo'=>696,	'nombre'=>'SANTA BARBARA',	'id_departamento'=>52,
                'codigo'=>699,	'nombre'=>'SANTACRUZ',	'id_departamento'=>52,
                'codigo'=>720,	'nombre'=>'SAPUYES',	'id_departamento'=>52,
                'codigo'=>786,	'nombre'=>'TAMINANGO',	'id_departamento'=>52,
                'codigo'=>788,	'nombre'=>'TANGUA',	'id_departamento'=>52,
                'codigo'=>835,	'nombre'=>'SAN ANDRES DE TUMACO',	'id_departamento'=>52,
                'codigo'=>838,	'nombre'=>'TUQUERRES',	'id_departamento'=>52,
                'codigo'=>885,	'nombre'=>'YACUANQUER',	'id_departamento'=>52,
                'codigo'=>1,	'nombre'=>'CUCUTA',	'id_departamento'=>54,
                'codigo'=>3,	'nombre'=>'ABREGO',	'id_departamento'=>54,
                'codigo'=>51,	'nombre'=>'ARBOLEDAS',	'id_departamento'=>54,
                'codigo'=>99,	'nombre'=>'BOCHALEMA',	'id_departamento'=>54,
                'codigo'=>109,	'nombre'=>'BUCARASICA',	'id_departamento'=>54,
                'codigo'=>125,	'nombre'=>'CACOTA',	'id_departamento'=>54,
                'codigo'=>128,	'nombre'=>'CACHIRA',	'id_departamento'=>54,
                'codigo'=>172,	'nombre'=>'CHINACOTA',	'id_departamento'=>54,
                'codigo'=>174,	'nombre'=>'CHITAGA',	'id_departamento'=>54,
                'codigo'=>206,	'nombre'=>'CONVENCION',	'id_departamento'=>54,
                'codigo'=>223,	'nombre'=>'CUCUTILLA',	'id_departamento'=>54,
                'codigo'=>239,	'nombre'=>'DURANIA',	'id_departamento'=>54,
                'codigo'=>245,	'nombre'=>'EL CARMEN',	'id_departamento'=>54,
                'codigo'=>250,	'nombre'=>'EL TARRA',	'id_departamento'=>54,
                'codigo'=>261,	'nombre'=>'EL ZULIA',	'id_departamento'=>54,
                'codigo'=>313,	'nombre'=>'GRAMALOTE',	'id_departamento'=>54,
                'codigo'=>344,	'nombre'=>'HACARI',	'id_departamento'=>54,
                'codigo'=>347,	'nombre'=>'HERRAN',	'id_departamento'=>54,
                'codigo'=>377,	'nombre'=>'LABATECA',	'id_departamento'=>54,
                'codigo'=>385,	'nombre'=>'LA ESPERANZA',	'id_departamento'=>54,
                'codigo'=>398,	'nombre'=>'LA PLAYA',	'id_departamento'=>54,
                'codigo'=>405,	'nombre'=>'LOS PATIOS',	'id_departamento'=>54,
                'codigo'=>418,	'nombre'=>'LOURDES',	'id_departamento'=>54,
                'codigo'=>480,	'nombre'=>'MUTISCUA',	'id_departamento'=>54,
                'codigo'=>498,	'nombre'=>'OCA?A',	'id_departamento'=>54,
                'codigo'=>518,	'nombre'=>'PAMPLONA',	'id_departamento'=>54,
                'codigo'=>520,	'nombre'=>'PAMPLONITA',	'id_departamento'=>54,
                'codigo'=>553,	'nombre'=>'PUERTO SANTANDER',	'id_departamento'=>54,
                'codigo'=>599,	'nombre'=>'RAGONVALIA',	'id_departamento'=>54,
                'codigo'=>660,	'nombre'=>'SALAZAR',	'id_departamento'=>54,
                'codigo'=>670,	'nombre'=>'SAN CALIXTO',	'id_departamento'=>54,
                'codigo'=>673,	'nombre'=>'SAN CAYETANO',	'id_departamento'=>54,
                'codigo'=>680,	'nombre'=>'SANTIAGO',	'id_departamento'=>54,
                'codigo'=>720,	'nombre'=>'SARDINATA',	'id_departamento'=>54,
                'codigo'=>743,	'nombre'=>'SILOS',	'id_departamento'=>54,
                'codigo'=>800,	'nombre'=>'TEORAMA',	'id_departamento'=>54,
                'codigo'=>810,	'nombre'=>'TIBU',	'id_departamento'=>54,
                'codigo'=>820,	'nombre'=>'TOLEDO',	'id_departamento'=>54,
                'codigo'=>871,	'nombre'=>'VILLA CARO',	'id_departamento'=>54,
                'codigo'=>874,	'nombre'=>'VILLA DEL ROSARIO',	'id_departamento'=>54,
                'codigo'=>1,	'nombre'=>'ARMENIA',	'id_departamento'=>63,
                'codigo'=>111,	'nombre'=>'BUENAVISTA',	'id_departamento'=>63,
                'codigo'=>130,	'nombre'=>'CALARCA',	'id_departamento'=>63,
                'codigo'=>190,	'nombre'=>'CIRCASIA',	'id_departamento'=>63,
                'codigo'=>212,	'nombre'=>'CORDOBA',	'id_departamento'=>63,
                'codigo'=>272,	'nombre'=>'FILANDIA',	'id_departamento'=>63,
                'codigo'=>302,	'nombre'=>'GENOVA',	'id_departamento'=>63,
                'codigo'=>401,	'nombre'=>'LA TEBAIDA',	'id_departamento'=>63,
                'codigo'=>470,	'nombre'=>'MONTENEGRO',	'id_departamento'=>63,
                'codigo'=>548,	'nombre'=>'PIJAO',	'id_departamento'=>63,
                'codigo'=>594,	'nombre'=>'QUIMBAYA',	'id_departamento'=>63,
                'codigo'=>690,	'nombre'=>'SALENTO',	'id_departamento'=>63,
                'codigo'=>1,	'nombre'=>'PEREIRA',	'id_departamento'=>66,
                'codigo'=>45,	'nombre'=>'APIA',	'id_departamento'=>66,
                'codigo'=>75,	'nombre'=>'BALBOA',	'id_departamento'=>66,
                'codigo'=>88,	'nombre'=>'BELEN DE UMBRIA',	'id_departamento'=>66,
                'codigo'=>170,	'nombre'=>'DOSQUEBRADAS',	'id_departamento'=>66,
                'codigo'=>318,	'nombre'=>'GUATICA',	'id_departamento'=>66,
                'codigo'=>383,	'nombre'=>'LA CELIA',	'id_departamento'=>66,
                'codigo'=>400,	'nombre'=>'LA VIRGINIA',	'id_departamento'=>66,
                'codigo'=>440,	'nombre'=>'MARSELLA',	'id_departamento'=>66,
                'codigo'=>456,	'nombre'=>'MISTRATO',	'id_departamento'=>66,
                'codigo'=>572,	'nombre'=>'PUEBLO RICO',	'id_departamento'=>66,
                'codigo'=>594,	'nombre'=>'QUINCHIA',	'id_departamento'=>66,
                'codigo'=>682,	'nombre'=>'SANTA ROSA DE CABAL',	'id_departamento'=>66,
                'codigo'=>687,	'nombre'=>'SANTUARIO',	'id_departamento'=>66,
                'codigo'=>1,	'nombre'=>'BUCARAMANGA',	'id_departamento'=>68,
                'codigo'=>13,	'nombre'=>'AGUADA',	'id_departamento'=>68,
                'codigo'=>20,	'nombre'=>'ALBANIA',	'id_departamento'=>68,
                'codigo'=>51,	'nombre'=>'ARATOCA',	'id_departamento'=>68,
                'codigo'=>77,	'nombre'=>'BARBOSA',	'id_departamento'=>68,
                'codigo'=>79,	'nombre'=>'BARICHARA',	'id_departamento'=>68,
                'codigo'=>81,	'nombre'=>'BARRANCABERMEJA',	'id_departamento'=>68,
                'codigo'=>92,	'nombre'=>'BETULIA',	'id_departamento'=>68,
                'codigo'=>101,	'nombre'=>'BOLIVAR',	'id_departamento'=>68,
                'codigo'=>121,	'nombre'=>'CABRERA',	'id_departamento'=>68,
                'codigo'=>132,	'nombre'=>'CALIFORNIA',	'id_departamento'=>68,
                'codigo'=>147,	'nombre'=>'CAPITANEJO',	'id_departamento'=>68,
                'codigo'=>152,	'nombre'=>'CARCASI',	'id_departamento'=>68,
                'codigo'=>160,	'nombre'=>'CEPITA',	'id_departamento'=>68,
                'codigo'=>162,	'nombre'=>'CERRITO',	'id_departamento'=>68,
                'codigo'=>167,	'nombre'=>'CHARALA',	'id_departamento'=>68,
                'codigo'=>169,	'nombre'=>'CHARTA',	'id_departamento'=>68,
                'codigo'=>176,	'nombre'=>'CHIMA',	'id_departamento'=>68,
                'codigo'=>179,	'nombre'=>'CHIPATA',	'id_departamento'=>68,
                'codigo'=>190,	'nombre'=>'CIMITARRA',	'id_departamento'=>68,
                'codigo'=>207,	'nombre'=>'CONCEPCION',	'id_departamento'=>68,
                'codigo'=>209,	'nombre'=>'CONFINES',	'id_departamento'=>68,
                'codigo'=>211,	'nombre'=>'CONTRATACION',	'id_departamento'=>68,
                'codigo'=>217,	'nombre'=>'COROMORO',	'id_departamento'=>68,
                'codigo'=>229,	'nombre'=>'CURITI',	'id_departamento'=>68,
                'codigo'=>235,	'nombre'=>'EL CARMEN DE CHUCURI',	'id_departamento'=>68,
                'codigo'=>245,	'nombre'=>'EL GUACAMAYO',	'id_departamento'=>68,
                'codigo'=>250,	'nombre'=>'EL PE?ON',	'id_departamento'=>68,
                'codigo'=>255,	'nombre'=>'EL PLAYON',	'id_departamento'=>68,
                'codigo'=>264,	'nombre'=>'ENCINO',	'id_departamento'=>68,
                'codigo'=>266,	'nombre'=>'ENCISO',	'id_departamento'=>68,
                'codigo'=>271,	'nombre'=>'FLORIAN',	'id_departamento'=>68,
                'codigo'=>276,	'nombre'=>'FLORIDABLANCA',	'id_departamento'=>68,
                'codigo'=>296,	'nombre'=>'GALAN',	'id_departamento'=>68,
                'codigo'=>298,	'nombre'=>'GAMBITA',	'id_departamento'=>68,
                'codigo'=>307,	'nombre'=>'GIRON',	'id_departamento'=>68,
                'codigo'=>318,	'nombre'=>'GUACA',	'id_departamento'=>68,
                'codigo'=>320,	'nombre'=>'GUADALUPE',	'id_departamento'=>68,
                'codigo'=>322,	'nombre'=>'GUAPOTA',	'id_departamento'=>68,
                'codigo'=>324,	'nombre'=>'GUAVATA',	'id_departamento'=>68,
                'codigo'=>327,	'nombre'=>'GsEPSA',	'id_departamento'=>68,
                'codigo'=>344,	'nombre'=>'HATO',	'id_departamento'=>68,
                'codigo'=>368,	'nombre'=>'JESUS MARIA',	'id_departamento'=>68,
                'codigo'=>370,	'nombre'=>'JORDAN',	'id_departamento'=>68,
                'codigo'=>377,	'nombre'=>'LA BELLEZA',	'id_departamento'=>68,
                'codigo'=>385,	'nombre'=>'LANDAZURI',	'id_departamento'=>68,
                'codigo'=>397,	'nombre'=>'LA PAZ',	'id_departamento'=>68,
                'codigo'=>406,	'nombre'=>'LEBRIJA',	'id_departamento'=>68,
                'codigo'=>418,	'nombre'=>'LOS SANTOS',	'id_departamento'=>68,
                'codigo'=>425,	'nombre'=>'MACARAVITA',	'id_departamento'=>68,
                'codigo'=>432,	'nombre'=>'MALAGA',	'id_departamento'=>68,
                'codigo'=>444,	'nombre'=>'MATANZA',	'id_departamento'=>68,
                'codigo'=>464,	'nombre'=>'MOGOTES',	'id_departamento'=>68,
                'codigo'=>468,	'nombre'=>'MOLAGAVITA',	'id_departamento'=>68,
                'codigo'=>498,	'nombre'=>'OCAMONTE',	'id_departamento'=>68,
                'codigo'=>500,	'nombre'=>'OIBA',	'id_departamento'=>68,
                'codigo'=>502,	'nombre'=>'ONZAGA',	'id_departamento'=>68,
                'codigo'=>522,	'nombre'=>'PALMAR',	'id_departamento'=>68,
                'codigo'=>524,	'nombre'=>'PALMAS DEL SOCORRO',	'id_departamento'=>68,
                'codigo'=>533,	'nombre'=>'PARAMO',	'id_departamento'=>68,
                'codigo'=>547,	'nombre'=>'PIEDECUESTA',	'id_departamento'=>68,
                'codigo'=>549,	'nombre'=>'PINCHOTE',	'id_departamento'=>68,
                'codigo'=>572,	'nombre'=>'PUENTE NACIONAL',	'id_departamento'=>68,
                'codigo'=>573,	'nombre'=>'PUERTO PARRA',	'id_departamento'=>68,
                'codigo'=>575,	'nombre'=>'PUERTO WILCHES',	'id_departamento'=>68,
                'codigo'=>615,	'nombre'=>'RIONEGRO',	'id_departamento'=>68,
                'codigo'=>655,	'nombre'=>'SABANA DE TORRES',	'id_departamento'=>68,
                'codigo'=>669,	'nombre'=>'SAN ANDRES',	'id_departamento'=>68,
                'codigo'=>673,	'nombre'=>'SAN BENITO',	'id_departamento'=>68,
                'codigo'=>679,	'nombre'=>'SAN GIL',	'id_departamento'=>68,
                'codigo'=>682,	'nombre'=>'SAN JOAQUIN',	'id_departamento'=>68,
                'codigo'=>684,	'nombre'=>'SAN JOSE DE MIRANDA',	'id_departamento'=>68,
                'codigo'=>686,	'nombre'=>'SAN MIGUEL',	'id_departamento'=>68,
                'codigo'=>689,	'nombre'=>'SAN VICENTE DE CHUCURI',	'id_departamento'=>68,
                'codigo'=>705,	'nombre'=>'SANTA BARBARA',	'id_departamento'=>68,
                'codigo'=>720,	'nombre'=>'SANTA HELENA DEL OPON',	'id_departamento'=>68,
                'codigo'=>745,	'nombre'=>'SIMACOTA',	'id_departamento'=>68,
                'codigo'=>755,	'nombre'=>'SOCORRO',	'id_departamento'=>68,
                'codigo'=>770,	'nombre'=>'SUAITA',	'id_departamento'=>68,
                'codigo'=>773,	'nombre'=>'SUCRE',	'id_departamento'=>68,
                'codigo'=>780,	'nombre'=>'SURATA',	'id_departamento'=>68,
                'codigo'=>820,	'nombre'=>'TONA',	'id_departamento'=>68,
                'codigo'=>855,	'nombre'=>'VALLE DE SAN JOSE',	'id_departamento'=>68,
                'codigo'=>861,	'nombre'=>'VELEZ',	'id_departamento'=>68,
                'codigo'=>867,	'nombre'=>'VETAS',	'id_departamento'=>68,
                'codigo'=>872,	'nombre'=>'VILLANUEVA',	'id_departamento'=>68,
                'codigo'=>895,	'nombre'=>'ZAPATOCA',	'id_departamento'=>68,
                'codigo'=>1,	'nombre'=>'SINCELEJO',	'id_departamento'=>70,
                'codigo'=>110,	'nombre'=>'BUENAVISTA',	'id_departamento'=>70,
                'codigo'=>124,	'nombre'=>'CAIMITO',	'id_departamento'=>70,
                'codigo'=>204,	'nombre'=>'COLOSO',	'id_departamento'=>70,
                'codigo'=>215,	'nombre'=>'COROZAL',	'id_departamento'=>70,
                'codigo'=>221,	'nombre'=>'COVE?AS',	'id_departamento'=>70,
                'codigo'=>230,	'nombre'=>'CHALAN',	'id_departamento'=>70,
                'codigo'=>233,	'nombre'=>'EL ROBLE',	'id_departamento'=>70,
                'codigo'=>235,	'nombre'=>'GALERAS',	'id_departamento'=>70,
                'codigo'=>265,	'nombre'=>'GUARANDA',	'id_departamento'=>70,
                'codigo'=>400,	'nombre'=>'LA UNION',	'id_departamento'=>70,
                'codigo'=>418,	'nombre'=>'LOS PALMITOS',	'id_departamento'=>70,
                'codigo'=>429,	'nombre'=>'MAJAGUAL',	'id_departamento'=>70,
                'codigo'=>473,	'nombre'=>'MORROA',	'id_departamento'=>70,
                'codigo'=>508,	'nombre'=>'OVEJAS',	'id_departamento'=>70,
                'codigo'=>523,	'nombre'=>'PALMITO',	'id_departamento'=>70,
                'codigo'=>670,	'nombre'=>'SAMPUES',	'id_departamento'=>70,
                'codigo'=>678,	'nombre'=>'SAN BENITO ABAD',	'id_departamento'=>70,
                'codigo'=>702,	'nombre'=>'SAN JUAN DE BETULIA',	'id_departamento'=>70,
                'codigo'=>708,	'nombre'=>'SAN MARCOS',	'id_departamento'=>70,
                'codigo'=>713,	'nombre'=>'SAN ONOFRE',	'id_departamento'=>70,
                'codigo'=>717,	'nombre'=>'SAN PEDRO',	'id_departamento'=>70,
                'codigo'=>742,	'nombre'=>'SAN LUIS DE SINCE',	'id_departamento'=>70,
                'codigo'=>771,	'nombre'=>'SUCRE',	'id_departamento'=>70,
                'codigo'=>820,	'nombre'=>'SANTIAGO DE TOLU',	'id_departamento'=>70,
                'codigo'=>823,	'nombre'=>'TOLU VIEJO',	'id_departamento'=>70,
                'codigo'=>1,	'nombre'=>'IBAGUE',	'id_departamento'=>73,
                'codigo'=>24,	'nombre'=>'ALPUJARRA',	'id_departamento'=>73,
                'codigo'=>26,	'nombre'=>'ALVARADO',	'id_departamento'=>73,
                'codigo'=>30,	'nombre'=>'AMBALEMA',	'id_departamento'=>73,
                'codigo'=>43,	'nombre'=>'ANZOATEGUI',	'id_departamento'=>73,
                'codigo'=>55,	'nombre'=>'ARMERO',	'id_departamento'=>73,
                'codigo'=>67,	'nombre'=>'ATACO',	'id_departamento'=>73,
                'codigo'=>124,	'nombre'=>'CAJAMARCA',	'id_departamento'=>73,
                'codigo'=>148,	'nombre'=>'CARMEN DE APICALA',	'id_departamento'=>73,
                'codigo'=>152,	'nombre'=>'CASABIANCA',	'id_departamento'=>73,
                'codigo'=>168,	'nombre'=>'CHAPARRAL',	'id_departamento'=>73,
                'codigo'=>200,	'nombre'=>'COELLO',	'id_departamento'=>73,
                'codigo'=>217,	'nombre'=>'COYAIMA',	'id_departamento'=>73,
                'codigo'=>226,	'nombre'=>'CUNDAY',	'id_departamento'=>73,
                'codigo'=>236,	'nombre'=>'DOLORES',	'id_departamento'=>73,
                'codigo'=>268,	'nombre'=>'ESPINAL',	'id_departamento'=>73,
                'codigo'=>270,	'nombre'=>'FALAN',	'id_departamento'=>73,
                'codigo'=>275,	'nombre'=>'FLANDES',	'id_departamento'=>73,
                'codigo'=>283,	'nombre'=>'FRESNO',	'id_departamento'=>73,
                'codigo'=>319,	'nombre'=>'GUAMO',	'id_departamento'=>73,
                'codigo'=>347,	'nombre'=>'HERVEO',	'id_departamento'=>73,
                'codigo'=>349,	'nombre'=>'HONDA',	'id_departamento'=>73,
                'codigo'=>352,	'nombre'=>'ICONONZO',	'id_departamento'=>73,
                'codigo'=>408,	'nombre'=>'LERIDA',	'id_departamento'=>73,
                'codigo'=>411,	'nombre'=>'LIBANO',	'id_departamento'=>73,
                'codigo'=>443,	'nombre'=>'MARIQUITA',	'id_departamento'=>73,
                'codigo'=>449,	'nombre'=>'MELGAR',	'id_departamento'=>73,
                'codigo'=>461,	'nombre'=>'MURILLO',	'id_departamento'=>73,
                'codigo'=>483,	'nombre'=>'NATAGAIMA',	'id_departamento'=>73,
                'codigo'=>504,	'nombre'=>'ORTEGA',	'id_departamento'=>73,
                'codigo'=>520,	'nombre'=>'PALOCABILDO',	'id_departamento'=>73,
                'codigo'=>547,	'nombre'=>'PIEDRAS',	'id_departamento'=>73,
                'codigo'=>555,	'nombre'=>'PLANADAS',	'id_departamento'=>73,
                'codigo'=>563,	'nombre'=>'PRADO',	'id_departamento'=>73,
                'codigo'=>585,	'nombre'=>'PURIFICACION',	'id_departamento'=>73,
                'codigo'=>616,	'nombre'=>'RIOBLANCO',	'id_departamento'=>73,
                'codigo'=>622,	'nombre'=>'RONCESVALLES',	'id_departamento'=>73,
                'codigo'=>624,	'nombre'=>'ROVIRA',	'id_departamento'=>73,
                'codigo'=>671,	'nombre'=>'SALDA?A',	'id_departamento'=>73,
                'codigo'=>675,	'nombre'=>'SAN ANTONIO',	'id_departamento'=>73,
                'codigo'=>678,	'nombre'=>'SAN LUIS',	'id_departamento'=>73,
                'codigo'=>686,	'nombre'=>'SANTA ISABEL',	'id_departamento'=>73,
                'codigo'=>770,	'nombre'=>'SUAREZ',	'id_departamento'=>73,
                'codigo'=>854,	'nombre'=>'VALLE DE SAN JUAN',	'id_departamento'=>73,
                'codigo'=>861,	'nombre'=>'VENADILLO',	'id_departamento'=>73,
                'codigo'=>870,	'nombre'=>'VILLAHERMOSA',	'id_departamento'=>73,
                'codigo'=>873,	'nombre'=>'VILLARRICA',	'id_departamento'=>73,
                'codigo'=>1,	'nombre'=>'CALI',	'id_departamento'=>76,
                'codigo'=>20,	'nombre'=>'ALCALA',	'id_departamento'=>76,
                'codigo'=>36,	'nombre'=>'ANDALUCIA',	'id_departamento'=>76,
                'codigo'=>41,	'nombre'=>'ANSERMANUEVO',	'id_departamento'=>76,
                'codigo'=>54,	'nombre'=>'ARGELIA',	'id_departamento'=>76,
                'codigo'=>100,	'nombre'=>'BOLIVAR',	'id_departamento'=>76,
                'codigo'=>109,	'nombre'=>'BUENAVENTURA',	'id_departamento'=>76,
                'codigo'=>111,	'nombre'=>'GUADALAJARA DE BUGA',	'id_departamento'=>76,
                'codigo'=>113,	'nombre'=>'BUGALAGRANDE',	'id_departamento'=>76,
                'codigo'=>122,	'nombre'=>'CAICEDONIA',	'id_departamento'=>76,
                'codigo'=>126,	'nombre'=>'CALIMA',	'id_departamento'=>76,
                'codigo'=>130,	'nombre'=>'CANDELARIA',	'id_departamento'=>76,
                'codigo'=>147,	'nombre'=>'CARTAGO',	'id_departamento'=>76,
                'codigo'=>233,	'nombre'=>'DAGUA',	'id_departamento'=>76,
                'codigo'=>243,	'nombre'=>'EL AGUILA',	'id_departamento'=>76,
                'codigo'=>246,	'nombre'=>'EL CAIRO',	'id_departamento'=>76,
                'codigo'=>248,	'nombre'=>'EL CERRITO',	'id_departamento'=>76,
                'codigo'=>250,	'nombre'=>'EL DOVIO',	'id_departamento'=>76,
                'codigo'=>275,	'nombre'=>'FLORIDA',	'id_departamento'=>76,
                'codigo'=>306,	'nombre'=>'GINEBRA',	'id_departamento'=>76,
                'codigo'=>318,	'nombre'=>'GUACARI',	'id_departamento'=>76,
                'codigo'=>364,	'nombre'=>'JAMUNDI',	'id_departamento'=>76,
                'codigo'=>377,	'nombre'=>'LA CUMBRE',	'id_departamento'=>76,
                'codigo'=>400,	'nombre'=>'LA UNION',	'id_departamento'=>76,
                'codigo'=>403,	'nombre'=>'LA VICTORIA',	'id_departamento'=>76,
                'codigo'=>497,	'nombre'=>'OBANDO',	'id_departamento'=>76,
                'codigo'=>520,	'nombre'=>'PALMIRA',	'id_departamento'=>76,
                'codigo'=>563,	'nombre'=>'PRADERA',	'id_departamento'=>76,
                'codigo'=>606,	'nombre'=>'RESTREPO',	'id_departamento'=>76,
                'codigo'=>616,	'nombre'=>'RIOFRIO',	'id_departamento'=>76,
                'codigo'=>622,	'nombre'=>'ROLDANILLO',	'id_departamento'=>76,
                'codigo'=>670,	'nombre'=>'SAN PEDRO',	'id_departamento'=>76,
                'codigo'=>736,	'nombre'=>'SEVILLA',	'id_departamento'=>76,
                'codigo'=>823,	'nombre'=>'TORO',	'id_departamento'=>76,
                'codigo'=>828,	'nombre'=>'TRUJILLO',	'id_departamento'=>76,
                'codigo'=>834,	'nombre'=>'TULUA',	'id_departamento'=>76,
                'codigo'=>845,	'nombre'=>'ULLOA',	'id_departamento'=>76,
                'codigo'=>863,	'nombre'=>'VERSALLES',	'id_departamento'=>76,
                'codigo'=>869,	'nombre'=>'VIJES',	'id_departamento'=>76,
                'codigo'=>890,	'nombre'=>'YOTOCO',	'id_departamento'=>76,
                'codigo'=>892,	'nombre'=>'YUMBO',	'id_departamento'=>76,
                'codigo'=>895,	'nombre'=>'ZARZAL',	'id_departamento'=>76,
                'codigo'=>1,	'nombre'=>'ARAUCA',	'id_departamento'=>81,
                'codigo'=>65,	'nombre'=>'ARAUQUITA',	'id_departamento'=>81,
                'codigo'=>220,	'nombre'=>'CRAVO NORTE',	'id_departamento'=>81,
                'codigo'=>300,	'nombre'=>'FORTUL',	'id_departamento'=>81,
                'codigo'=>591,	'nombre'=>'PUERTO RONDON',	'id_departamento'=>81,
                'codigo'=>736,	'nombre'=>'SARAVENA',	'id_departamento'=>81,
                'codigo'=>794,	'nombre'=>'TAME',	'id_departamento'=>81,
                'codigo'=>1,	'nombre'=>'YOPAL',	'id_departamento'=>85,
                'codigo'=>10,	'nombre'=>'AGUAZUL',	'id_departamento'=>85,
                'codigo'=>15,	'nombre'=>'CHAMEZA',	'id_departamento'=>85,
                'codigo'=>125,	'nombre'=>'HATO COROZAL',	'id_departamento'=>85,
                'codigo'=>136,	'nombre'=>'LA SALINA',	'id_departamento'=>85,
                'codigo'=>139,	'nombre'=>'MANI',	'id_departamento'=>85,
                'codigo'=>162,	'nombre'=>'MONTERREY',	'id_departamento'=>85,
                'codigo'=>225,	'nombre'=>'NUNCHIA',	'id_departamento'=>85,
                'codigo'=>230,	'nombre'=>'OROCUE',	'id_departamento'=>85,
                'codigo'=>250,	'nombre'=>'PAZ DE ARIPORO',	'id_departamento'=>85,
                'codigo'=>263,	'nombre'=>'PORE',	'id_departamento'=>85,
                'codigo'=>279,	'nombre'=>'RECETOR',	'id_departamento'=>85,
                'codigo'=>300,	'nombre'=>'SABANALARGA',	'id_departamento'=>85,
                'codigo'=>315,	'nombre'=>'SACAMA',	'id_departamento'=>85,
                'codigo'=>325,	'nombre'=>'SAN LUIS DE PALENQUE',	'id_departamento'=>85,
                'codigo'=>400,	'nombre'=>'TAMARA',	'id_departamento'=>85,
                'codigo'=>410,	'nombre'=>'TAURAMENA',	'id_departamento'=>85,
                'codigo'=>430,	'nombre'=>'TRINIDAD',	'id_departamento'=>85,
                'codigo'=>440,	'nombre'=>'VILLANUEVA',	'id_departamento'=>85,
                'codigo'=>1,	'nombre'=>'MOCOA',	'id_departamento'=>86,
                'codigo'=>219,	'nombre'=>'COLON',	'id_departamento'=>86,
                'codigo'=>320,	'nombre'=>'ORITO',	'id_departamento'=>86,
                'codigo'=>568,	'nombre'=>'PUERTO ASIS',	'id_departamento'=>86,
                'codigo'=>569,	'nombre'=>'PUERTO CAICEDO',	'id_departamento'=>86,
                'codigo'=>571,	'nombre'=>'PUERTO GUZMAN',	'id_departamento'=>86,
                'codigo'=>573,	'nombre'=>'LEGUIZAMO',	'id_departamento'=>86,
                'codigo'=>749,	'nombre'=>'SIBUNDOY',	'id_departamento'=>86,
                'codigo'=>755,	'nombre'=>'SAN FRANCISCO',	'id_departamento'=>86,
                'codigo'=>757,	'nombre'=>'SAN MIGUEL',	'id_departamento'=>86,
                'codigo'=>760,	'nombre'=>'SANTIAGO',	'id_departamento'=>86,
                'codigo'=>865,	'nombre'=>'VALLE DEL GUAMUEZ',	'id_departamento'=>86,
                'codigo'=>885,	'nombre'=>'VILLAGARZON',	'id_departamento'=>86,
                'codigo'=>1,	'nombre'=>'SAN ANDRES',	'id_departamento'=>88,
                'codigo'=>564,	'nombre'=>'PROVIDENCIA',	'id_departamento'=>88,
                'codigo'=>1,	'nombre'=>'LETICIA',	'id_departamento'=>91,
                'codigo'=>263,	'nombre'=>'EL ENCANTO',	'id_departamento'=>91,
                'codigo'=>405,	'nombre'=>'LA CHORRERA',	'id_departamento'=>91,
                'codigo'=>407,	'nombre'=>'LA PEDRERA',	'id_departamento'=>91,
                'codigo'=>430,	'nombre'=>'LA VICTORIA',	'id_departamento'=>91,
                'codigo'=>460,	'nombre'=>'MIRITI - PARANA',	'id_departamento'=>91,
                'codigo'=>530,	'nombre'=>'PUERTO ALEGRIA',	'id_departamento'=>91,
                'codigo'=>536,	'nombre'=>'PUERTO ARICA',	'id_departamento'=>91,
                'codigo'=>540,	'nombre'=>'PUERTO NARI?O',	'id_departamento'=>91,
                'codigo'=>669,	'nombre'=>'PUERTO SANTANDER',	'id_departamento'=>91,
                'codigo'=>798,	'nombre'=>'TARAPACA',	'id_departamento'=>91,
                'codigo'=>1,	'nombre'=>'INIRIDA',	'id_departamento'=>94,
                'codigo'=>343,	'nombre'=>'BARRANCO MINAS',	'id_departamento'=>94,
                'codigo'=>663,	'nombre'=>'MAPIRIPANA',	'id_departamento'=>94,
                'codigo'=>883,	'nombre'=>'SAN FELIPE',	'id_departamento'=>94,
                'codigo'=>884,	'nombre'=>'PUERTO COLOMBIA',	'id_departamento'=>94,
                'codigo'=>885,	'nombre'=>'LA GUADALUPE',	'id_departamento'=>94,
                'codigo'=>886,	'nombre'=>'CACAHUAL',	'id_departamento'=>94,
                'codigo'=>887,	'nombre'=>'PANA PANA',	'id_departamento'=>94,
                'codigo'=>888,	'nombre'=>'MORICHAL',	'id_departamento'=>94,
                'codigo'=>1,	'nombre'=>'SAN JOSE DEL GUAVIARE',	'id_departamento'=>95,
                'codigo'=>15,	'nombre'=>'CALAMAR',	'id_departamento'=>95,
                'codigo'=>25,	'nombre'=>'EL RETORNO',	'id_departamento'=>95,
                'codigo'=>200,	'nombre'=>'MIRAFLORES',	'id_departamento'=>95,
                'codigo'=>1,	'nombre'=>'MITU',	'id_departamento'=>97,
                'codigo'=>161,	'nombre'=>'CARURU',	'id_departamento'=>97,
                'codigo'=>511,	'nombre'=>'PACOA',	'id_departamento'=>97,
                'codigo'=>666,	'nombre'=>'TARAIRA',	'id_departamento'=>97,
                'codigo'=>777,	'nombre'=>'PAPUNAUA',	'id_departamento'=>97,
                'codigo'=>889,	'nombre'=>'YAVARATE',	'id_departamento'=>97,
                'codigo'=>1,	'nombre'=>'PUERTO CARRE?O',	'id_departamento'=>99,
                'codigo'=>524,	'nombre'=>'LA PRIMAVERA',	'id_departamento'=>99,
                'codigo'=>624,	'nombre'=>'SANTA ROSALIA',	'id_departamento'=>99,
                'codigo'=>773,	'nombre'=>'CUMARIBO',	'id_departamento'=>99,

            ]);
    }
}
